package gcs;

import Clases.ListaCarrito;
import Clases.ListaProductos;
import Clases.Producto;
import bdMYSQL.SqlProductos;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;


/**
 *
 * @author usuario
 */
public class Catalogo extends javax.swing.JFrame {
    SqlProductos consultaP = new SqlProductos();
    org.edisoncor.gui.panel.PanelImage [] paneles = new  org.edisoncor.gui.panel.PanelImage [42];
    javax.swing.JLabel [] labels = new javax.swing.JLabel[42];
    Producto [] producto = new Producto [6];
    int posInicial = 0; 
    String tipo;
    //Patron Singleton
    private static Catalogo instance;
    
    public Catalogo(){
        initComponents();
        llenarMatriz();
        consultaP.ObtenerProducto();
        instance = this;
        setLocationRelativeTo(null);
        setResizable(false);
        lblCantCarrito.setText("" + ListaCarrito.getSize());
    }

    public void actualizarCarrito (){
        lblCantCarrito.setText("" + ListaCarrito.getSize());
    }

    public void buscador(boolean modo){
        pnlLupa.setVisible(modo);
        txtBuscar.setVisible(modo);
    }
    
    public void setLbl (String nombre){
        lblNombre.setText(nombre);
    }
    public static Catalogo getInstance() {
        if (instance == null) {
            instance = new Catalogo();
        }
        return instance;
    }
    
    public void activarCarrito (){
        Carrito carrito = new Carrito();
        carrito.setSize(980, 570);
        carrito.setLocation(0, 0);
        pnlCarritoCompra.removeAll();
        pnlCarritoCompra.add(carrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(0,0,-1,-1));
        pnlCarritoCompra.revalidate();
        pnlCarrito.repaint();
        cambPaneles.setSelectedIndex(2);
        carrito.setFrame(this);
    }
    
    public void setIndex (int i){
        cambPaneles.setSelectedIndex(i);
    }
    
    public void abrirCarrito(int ind){
        if (producto[ind] != null){
            AgregarCarrito agregar = new AgregarCarrito();
            agregar.iniciarComponentes(producto[ind]);
            if (producto[ind].getIdPromo()!= 0)
                agregar.setPromocion();
            agregar.setVisible(true);
            agregar.setFrame(this);
            agregar.toFront();
        }
    }
    
    public void seleccionP (List <Producto> art, String prod){
        int posFinal = Math.min(posInicial + 6, art.size());
        int j = 0;
        limpiarCatalogo();
        for (int i = posInicial; j < 6 && i < art.size(); i++) {
            if (art.get(i).getTipo().equals(prod)){
                String image = art.get(i).getImage();
                paneles[j].setIcon(new javax.swing.ImageIcon (getClass().getResource(image)));
                paneles[j].repaint();
                labels[j].setText(strHTML(art.get(i).getDescripcion()));
                producto[j] = art.get(i);
                j++;
            }
        }
        if(posFinal >= art.size() || j < 6){
            btnSiguiente.setEnabled(false);
        }
    }
    
    public void busquedaP (List <Producto> art, String termino){
        int posFinal = Math.min(posInicial + 6, art.size());
        int j = 0;
        boolean filtro;
        limpiarCatalogo();
        for (int i = posInicial; j < 6 && i < art.size(); i++) {
            filtro = art.get(i).getTipo().equals(tipo);
            if (art.get(i).getDescripcion().toLowerCase().contains(termino.toLowerCase()) && filtro){
                String image = art.get(i).getImage();
                paneles[j].setIcon(new javax.swing.ImageIcon (getClass().getResource(image)));
                paneles[j].repaint();
                labels[j].setText(art.get(i).getDescripcion());
                producto[j] = art.get(i);
                j++;
            }
        }
        if(posFinal >= art.size() || j < 6){
            btnSiguiente.setEnabled(false);
        }
    }
    
    public void llenarCatalogo (ArrayList <Producto> art){
        int i = 0;
        for (Producto articulo : art) {
            paneles[i].setIcon(new javax.swing.ImageIcon (getClass().getResource(articulo.getImage())));
            paneles[i].repaint();
            labels[i].setText(articulo.getDescripcion());
            i++;
        }
    }
    public void limpiarCatalogo(){
        for (int i = 0; i < 6; i++){
            paneles[i].setIcon(new javax.swing.ImageIcon (getClass().getResource("/imagenes/delete.jpg")));
            paneles[i].repaint();
            labels[i].setText("");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        pnlLupa = new org.edisoncor.gui.panel.PanelImage();
        jPanel1 = new javax.swing.JPanel();
        pnlCategoria = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        panelImage4 = new org.edisoncor.gui.panel.PanelImage();
        pnlMisCompras = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        panelImage3 = new org.edisoncor.gui.panel.PanelImage();
        pnlCarrito = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        images.PanelRound1 cantCarrito = new images.PanelRound1();
        lblCantCarrito = new javax.swing.JLabel();
        pnlSalir = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelImage5 = new org.edisoncor.gui.panel.PanelImage();
        lblBienvenido = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jLabel14 = new javax.swing.JLabel();
        cambPaneles = new javax.swing.JTabbedPane();
        pnlCategorias = new javax.swing.JPanel();
        pnlTarjetasG = new javax.swing.JPanel();
        pnlProcesadores = new javax.swing.JPanel();
        pnlMouses = new javax.swing.JPanel();
        pnlImpresoras = new javax.swing.JPanel();
        pnlAuriculares = new javax.swing.JPanel();
        pnlTeclados = new javax.swing.JPanel();
        lblTeclados = new javax.swing.JLabel();
        lblTarjetaG = new javax.swing.JLabel();
        lblProcesador = new javax.swing.JLabel();
        lblMouse = new javax.swing.JLabel();
        lblImpresora = new javax.swing.JLabel();
        lblAuricular = new javax.swing.JLabel();
        imgTarjeta = new javax.swing.JLabel();
        imgProcesadores = new javax.swing.JLabel();
        imgMouse = new javax.swing.JLabel();
        imgImpresora = new javax.swing.JLabel();
        imgAuriculares = new javax.swing.JLabel();
        imgTeclado = new javax.swing.JLabel();
        pnlPestañaP1 = new javax.swing.JPanel();
        imProducto1 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto1 = new javax.swing.JLabel();
        imProducto2 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto2 = new javax.swing.JLabel();
        imProducto3 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto3 = new javax.swing.JLabel();
        imProducto4 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto4 = new javax.swing.JLabel();
        imProducto6 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto5 = new javax.swing.JLabel();
        imProducto5 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto6 = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        pnlCarritoCompra = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblName.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("TECHSALES");
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 230, 40));

        txtBuscar.setBackground(new java.awt.Color(228, 228, 228));
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });
        txtBuscar.setVisible(false);
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 90, 330, 30));

        pnlLupa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.png"))); // NOI18N
        pnlLupa.setVisible(false);
        getContentPane().add(pnlLupa, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 80, 50, 50));

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCategoria.setBackground(new java.awt.Color(255, 153, 0));
        pnlCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlCategoriaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlCategoriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlCategoriaMouseExited(evt);
            }
        });
        pnlCategoria.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setBackground(new java.awt.Color(255, 255, 255));
        jLabel49.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("CATEGORÍAS");
        pnlCategoria.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 110, 30));

        panelImage4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/categoria.png"))); // NOI18N
        pnlCategoria.add(panelImage4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 13, 65, 65));

        jPanel1.add(pnlCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 300, 90));

        pnlMisCompras.setBackground(new java.awt.Color(255, 153, 0));
        pnlMisCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMisComprasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlMisComprasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlMisComprasMouseExited(evt);
            }
        });
        pnlMisCompras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("MIS COMPRAS");
        pnlMisCompras.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 120, 30));

        panelImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/compra1.png"))); // NOI18N
        pnlMisCompras.add(panelImage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 13, 65, 65));

        jPanel1.add(pnlMisCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 300, 90));

        pnlCarrito.setBackground(new java.awt.Color(255, 153, 0));
        pnlCarrito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlCarritoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlCarritoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlCarritoMouseExited(evt);
            }
        });
        pnlCarrito.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CARRITO");
        pnlCarrito.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 27, 110, 30));

        panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carrito2.png"))); // NOI18N
        pnlCarrito.add(panelImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 65, 65));

        cantCarrito.setBackground(new java.awt.Color(234, 84, 85));
        cantCarrito.setRoundBottomLeft(40);
        cantCarrito.setRoundBottomRight(40);
        cantCarrito.setRoundTopLeft(40);
        cantCarrito.setRoundTopRight(40);
        cantCarrito.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCantCarrito.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCantCarrito.setForeground(new java.awt.Color(255, 255, 255));
        lblCantCarrito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantCarrito.add(lblCantCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        pnlCarrito.add(cantCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 25, 40, 40));

        jPanel1.add(pnlCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 300, 80));

        pnlSalir.setBackground(new java.awt.Color(255, 153, 0));
        pnlSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSalirMouseExited(evt);
            }
        });
        pnlSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SALIR");
        pnlSalir.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 28, 110, 30));

        panelImage5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir0.png"))); // NOI18N
        pnlSalir.add(panelImage5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 65, 65));

        jPanel1.add(pnlSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 300, 80));

        lblBienvenido.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblBienvenido.setForeground(new java.awt.Color(235, 235, 235));
        lblBienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBienvenido.setText("BIENVENIDO");
        jPanel1.add(lblBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 120, 40));

        lblNombre.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(235, 235, 235));
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 220, 40));

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SOLOiconEmpresa.png"))); // NOI18N
        jPanel1.add(panelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 45, 65, 65));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 700));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ff9911.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 990, 150));

        pnlCategorias.setBackground(new java.awt.Color(255, 255, 255));
        pnlCategorias.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTarjetasG.setBackground(new java.awt.Color(255, 255, 255));
        pnlTarjetasG.setOpaque(false);
        pnlTarjetasG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTarjetasGMouseClicked(evt);
            }
        });
        pnlTarjetasG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlCategorias.add(pnlTarjetasG, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 200, 220));

        pnlProcesadores.setBackground(new java.awt.Color(255, 255, 255));
        pnlProcesadores.setOpaque(false);
        pnlProcesadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlProcesadoresMouseClicked(evt);
            }
        });
        pnlProcesadores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlCategorias.add(pnlProcesadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 200, 220));

        pnlMouses.setBackground(new java.awt.Color(255, 255, 255));
        pnlMouses.setOpaque(false);
        pnlMouses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMousesMouseClicked(evt);
            }
        });
        pnlMouses.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlCategorias.add(pnlMouses, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, 190, 230));

        pnlImpresoras.setBackground(new java.awt.Color(255, 255, 255));
        pnlImpresoras.setOpaque(false);
        pnlImpresoras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlImpresorasMouseClicked(evt);
            }
        });
        pnlImpresoras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlCategorias.add(pnlImpresoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 210, 240));

        pnlAuriculares.setBackground(new java.awt.Color(255, 255, 255));
        pnlAuriculares.setOpaque(false);
        pnlAuriculares.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAuricularesMouseClicked(evt);
            }
        });
        pnlAuriculares.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlCategorias.add(pnlAuriculares, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 210, 240));

        pnlTeclados.setBackground(new java.awt.Color(255, 255, 255));
        pnlTeclados.setOpaque(false);
        pnlTeclados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTecladosMouseClicked(evt);
            }
        });
        pnlTeclados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlCategorias.add(pnlTeclados, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 180, 210));

        lblTeclados.setBackground(new java.awt.Color(0, 0, 0));
        lblTeclados.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblTeclados.setForeground(new java.awt.Color(0, 0, 0));
        lblTeclados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTeclados.setText("TECLADOS");
        pnlCategorias.add(lblTeclados, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, 120, 30));

        lblTarjetaG.setBackground(new java.awt.Color(0, 0, 0));
        lblTarjetaG.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblTarjetaG.setForeground(new java.awt.Color(0, 0, 0));
        lblTarjetaG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTarjetaG.setText("TARJETAS GRAFICAS");
        pnlCategorias.add(lblTarjetaG, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 180, 30));

        lblProcesador.setBackground(new java.awt.Color(0, 0, 0));
        lblProcesador.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProcesador.setForeground(new java.awt.Color(0, 0, 0));
        lblProcesador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProcesador.setText("PROCESADORES");
        pnlCategorias.add(lblProcesador, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 140, 30));

        lblMouse.setBackground(new java.awt.Color(0, 0, 0));
        lblMouse.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblMouse.setForeground(new java.awt.Color(0, 0, 0));
        lblMouse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMouse.setText("MOUSE");
        pnlCategorias.add(lblMouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, 120, 30));

        lblImpresora.setBackground(new java.awt.Color(0, 0, 0));
        lblImpresora.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblImpresora.setForeground(new java.awt.Color(0, 0, 0));
        lblImpresora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImpresora.setText("IMPRESORAS");
        pnlCategorias.add(lblImpresora, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 120, 30));

        lblAuricular.setBackground(new java.awt.Color(0, 0, 0));
        lblAuricular.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblAuricular.setForeground(new java.awt.Color(0, 0, 0));
        lblAuricular.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAuricular.setText("AURICULARES");
        pnlCategorias.add(lblAuricular, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, 140, 30));

        imgTarjeta.setForeground(new java.awt.Color(0, 0, 0));
        imgTarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/asus.jpg"))); // NOI18N
        pnlCategorias.add(imgTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 180, -1));

        imgProcesadores.setForeground(new java.awt.Color(0, 0, 0));
        imgProcesadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/intel-core-i5165172.jpg"))); // NOI18N
        pnlCategorias.add(imgProcesadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 180, 190));

        imgMouse.setBackground(new java.awt.Color(255, 255, 255));
        imgMouse.setForeground(new java.awt.Color(0, 0, 0));
        imgMouse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/m3.jpg"))); // NOI18N
        pnlCategorias.add(imgMouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 140, -1));

        imgImpresora.setForeground(new java.awt.Color(0, 0, 0));
        imgImpresora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/impresora-epson-ecotank-l3210-multifuncional-pnc11cj68303-.jpg"))); // NOI18N
        pnlCategorias.add(imgImpresora, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 180, -1));

        imgAuriculares.setForeground(new java.awt.Color(0, 0, 0));
        imgAuriculares.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/auriculares.jpg"))); // NOI18N
        pnlCategorias.add(imgAuriculares, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 180, -1));

        imgTeclado.setBackground(new java.awt.Color(255, 255, 255));
        imgTeclado.setForeground(new java.awt.Color(0, 0, 0));
        imgTeclado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/te4.jpg"))); // NOI18N
        pnlCategorias.add(imgTeclado, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, 160, 160));

        cambPaneles.addTab("Categorias", pnlCategorias);

        pnlPestañaP1.setBackground(new java.awt.Color(255, 255, 255));
        pnlPestañaP1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imProducto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imProducto1MouseClicked(evt);
            }
        });
        imProducto1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP1.add(imProducto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 180, 180));

        lblProducto1.setBackground(new java.awt.Color(255, 255, 255));
        lblProducto1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblProducto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP1.add(lblProducto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 240, 44));

        imProducto2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imProducto2MouseClicked(evt);
            }
        });
        imProducto2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP1.add(imProducto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 180, 180));

        lblProducto2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblProducto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP1.add(lblProducto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 220, 44));

        imProducto3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imProducto3MouseClicked(evt);
            }
        });
        imProducto3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP1.add(imProducto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, 180, 180));

        lblProducto3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblProducto3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP1.add(lblProducto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 260, 44));

        imProducto4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imProducto4MouseClicked(evt);
            }
        });
        imProducto4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP1.add(imProducto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 180, 180));

        lblProducto4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblProducto4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP1.add(lblProducto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 240, 44));

        imProducto6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imProducto6MouseClicked(evt);
            }
        });
        imProducto6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP1.add(imProducto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 180, 180));

        lblProducto5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblProducto5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP1.add(lblProducto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 240, 44));

        imProducto5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imProducto5MouseClicked(evt);
            }
        });
        imProducto5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP1.add(imProducto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 180, 180));

        lblProducto6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblProducto6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP1.add(lblProducto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, 260, 44));

        btnSiguiente.setBackground(new java.awt.Color(255, 153, 0));
        btnSiguiente.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        btnSiguiente.setText("SIGUIENTE");
        btnSiguiente.setBorder(null);
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        pnlPestañaP1.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 390, 70, 60));

        btnAnterior.setBackground(new java.awt.Color(255, 153, 0));
        btnAnterior.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        btnAnterior.setText("ANTERIOR");
        btnAnterior.setBorder(null);
        btnAnterior.addActionListener(e -> btnAnteriorActionPerformed());
        pnlPestañaP1.add(btnAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 70, 60));

        cambPaneles.addTab("Productos 1", pnlPestañaP1);
        cambPaneles.addTab("tab3", pnlCarritoCompra);

        getContentPane().add(cambPaneles, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 990, 580));
        cambPaneles.getAccessibleContext().setAccessibleName("tab3");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void llenarMatriz(){
        paneles [0] = imProducto1;
        paneles [1] = imProducto2;
        paneles [2] = imProducto3;
        paneles [3] = imProducto4;
        paneles [4] = imProducto5;
        paneles [5] = imProducto6;
        labels [0] = lblProducto1;
        labels [1] = lblProducto2;
        labels [2] = lblProducto3;
        labels [3] = lblProducto4;
        labels [4] = lblProducto5;
        labels [5] = lblProducto6;
    }
    
    public String strHTML (String text){
        return "<html><p>" + text + "</p></html>";
    }
    
    private void filtrar(){
        buscador(true);
        seleccionP(ListaProductos.getDataList(),tipo);
        cambPaneles.setSelectedIndex(1);
    }
    
    private void pnlSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSalirMouseClicked
        int resp = JOptionPane.showConfirmDialog(null, "¿Está seguro de salir?");
        if (resp == 0){
            Login log = new Login();
            log.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_pnlSalirMouseClicked

    private void pnlCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCategoriaMouseClicked
        cambPaneles.setSelectedIndex(0);   
        btnSiguiente.setEnabled(true);
        buscador(false);
        posInicial = 0;
        for (int i = 0; i < 6; i++)
            producto [i] = null;
    }//GEN-LAST:event_pnlCategoriaMouseClicked

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        posInicial +=6;
        filtrar();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAnteriorActionPerformed() {                                            
        posInicial -=6;
        if (posInicial < 0){
            buscador(false);
            cambPaneles.setSelectedIndex(0);
            posInicial = 0;
        }else{
            btnAnterior.setEnabled(true);
            filtrar();
        }
    }     
    
    private void pnlProcesadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlProcesadoresMouseClicked
        tipo = "Procesador";
        filtrar(); 
    }//GEN-LAST:event_pnlProcesadoresMouseClicked

    private void pnlTarjetasGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTarjetasGMouseClicked
        tipo = "Tarjeta gráfica";
        filtrar();
        
    }//GEN-LAST:event_pnlTarjetasGMouseClicked

    private void pnlImpresorasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlImpresorasMouseClicked
        tipo = "Impresora";
        filtrar();
    }//GEN-LAST:event_pnlImpresorasMouseClicked

    private void pnlMousesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMousesMouseClicked
        tipo = "Mouse";
        filtrar();
    }//GEN-LAST:event_pnlMousesMouseClicked

    private void pnlAuricularesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAuricularesMouseClicked
        tipo = "Auricular";
        filtrar();
    }//GEN-LAST:event_pnlAuricularesMouseClicked

    private void pnlTecladosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTecladosMouseClicked
        tipo = "Teclado";
        filtrar();
    }//GEN-LAST:event_pnlTecladosMouseClicked
    
    private void pnlCarritoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCarritoMouseClicked
        pnlLupa.setVisible(false);
        txtBuscar.setVisible(false);
        activarCarrito();
    }//GEN-LAST:event_pnlCarritoMouseClicked

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        cambPaneles.setSelectedIndex(1); 
        String termino;
        termino = txtBuscar.getText();
        busquedaP(ListaProductos.getDataList(),termino);
        
    }//GEN-LAST:event_txtBuscarKeyTyped
    
    private void pnlMisComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMisComprasMouseClicked
        Reporte rep = Reporte.getInstance();
        rep.llenarTabla();
        rep.setVisible(true);
    }//GEN-LAST:event_pnlMisComprasMouseClicked
   
    private void imProducto1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imProducto1MouseClicked
       abrirCarrito(0);
    }//GEN-LAST:event_imProducto1MouseClicked

    private void imProducto2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imProducto2MouseClicked
        abrirCarrito(1);
    }//GEN-LAST:event_imProducto2MouseClicked

    private void imProducto3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imProducto3MouseClicked
        abrirCarrito(2);
    }//GEN-LAST:event_imProducto3MouseClicked

    private void imProducto4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imProducto4MouseClicked
        abrirCarrito(3);
    }//GEN-LAST:event_imProducto4MouseClicked

    private void imProducto5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imProducto5MouseClicked
        abrirCarrito(4);
    }//GEN-LAST:event_imProducto5MouseClicked

    private void imProducto6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imProducto6MouseClicked
        abrirCarrito(5);
    }//GEN-LAST:event_imProducto6MouseClicked

    private void pnlCategoriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCategoriaMouseEntered
        pnlCategoria.setBackground(new Color(255,169,40));
    }//GEN-LAST:event_pnlCategoriaMouseEntered

    private void pnlCategoriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCategoriaMouseExited
        pnlCategoria.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_pnlCategoriaMouseExited

    private void pnlMisComprasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMisComprasMouseEntered
        pnlMisCompras.setBackground(new Color(255,169,40));
    }//GEN-LAST:event_pnlMisComprasMouseEntered

    private void pnlMisComprasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMisComprasMouseExited
        pnlMisCompras.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_pnlMisComprasMouseExited

    private void pnlCarritoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCarritoMouseEntered
        pnlCarrito.setBackground(new Color(255,169,40));
    }//GEN-LAST:event_pnlCarritoMouseEntered

    private void pnlCarritoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCarritoMouseExited
        pnlCarrito.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_pnlCarritoMouseExited

    private void pnlSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSalirMouseEntered
        pnlSalir.setBackground(new Color(255,169,40));
    }//GEN-LAST:event_pnlSalirMouseEntered

    private void pnlSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSalirMouseExited
        pnlSalir.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_pnlSalirMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Catalogo().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JTabbedPane cambPaneles;
    private org.edisoncor.gui.panel.PanelImage imProducto1;
    private org.edisoncor.gui.panel.PanelImage imProducto2;
    private org.edisoncor.gui.panel.PanelImage imProducto3;
    private org.edisoncor.gui.panel.PanelImage imProducto4;
    private org.edisoncor.gui.panel.PanelImage imProducto5;
    private org.edisoncor.gui.panel.PanelImage imProducto6;
    private javax.swing.JLabel imgAuriculares;
    private javax.swing.JLabel imgImpresora;
    private javax.swing.JLabel imgMouse;
    private javax.swing.JLabel imgProcesadores;
    private javax.swing.JLabel imgTarjeta;
    private javax.swing.JLabel imgTeclado;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAuricular;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblCantCarrito;
    private javax.swing.JLabel lblImpresora;
    private javax.swing.JLabel lblMouse;
    private javax.swing.JLabel lblName;
    public javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblProcesador;
    private javax.swing.JLabel lblProducto1;
    private javax.swing.JLabel lblProducto2;
    private javax.swing.JLabel lblProducto3;
    private javax.swing.JLabel lblProducto4;
    private javax.swing.JLabel lblProducto5;
    private javax.swing.JLabel lblProducto6;
    private javax.swing.JLabel lblTarjetaG;
    private javax.swing.JLabel lblTeclados;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    private org.edisoncor.gui.panel.PanelImage panelImage3;
    private org.edisoncor.gui.panel.PanelImage panelImage4;
    private org.edisoncor.gui.panel.PanelImage panelImage5;
    private javax.swing.JPanel pnlAuriculares;
    private javax.swing.JPanel pnlCarrito;
    private javax.swing.JPanel pnlCarritoCompra;
    private javax.swing.JPanel pnlCategoria;
    private javax.swing.JPanel pnlCategorias;
    private javax.swing.JPanel pnlImpresoras;
    private org.edisoncor.gui.panel.PanelImage pnlLupa;
    private javax.swing.JPanel pnlMisCompras;
    private javax.swing.JPanel pnlMouses;
    private javax.swing.JPanel pnlPestañaP1;
    private javax.swing.JPanel pnlProcesadores;
    private javax.swing.JPanel pnlSalir;
    private javax.swing.JPanel pnlTarjetasG;
    private javax.swing.JPanel pnlTeclados;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
