/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gcs;

import Clases.ListaProductos;
import Clases.Producto;
import Clases.Promocion;
import bdMYSQL.ConexionBD;
import bdMYSQL.SqlProductos;
import bdMYSQL.SqlPromocion;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.nio.file.StandardCopyOption;
import java.sql.*;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.*;

/**
 *
 * @author usuario
 */
public class ventanaAdmin extends javax.swing.JFrame {
    File selectedFile;
    File destinationFile;
    private DefaultTableModel modelo;
    public ventanaAdmin() {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        llenarProductos();
        llenarTablaVentas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        lblHead = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblAdmin = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblNameAdmin = new javax.swing.JLabel();
        pnlRegi = new javax.swing.JPanel();
        lblRegi = new javax.swing.JLabel();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        pnlEdit = new javax.swing.JPanel();
        lblElim = new javax.swing.JLabel();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        pnlProm = new javax.swing.JPanel();
        lblEdit = new javax.swing.JLabel();
        panelImage3 = new org.edisoncor.gui.panel.PanelImage();
        pnlRepo = new javax.swing.JPanel();
        lblRepo = new javax.swing.JLabel();
        panelImage4 = new org.edisoncor.gui.panel.PanelImage();
        pnlSalir = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        panelImage5 = new org.edisoncor.gui.panel.PanelImage();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlRegistro = new javax.swing.JPanel();
        lblDescripcion = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        lblProducto = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        txtPrecU = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblPrecio = new javax.swing.JLabel();
        chooseFile = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        lblStock = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        cboTipo = new javax.swing.JComboBox<>();
        pnlEdicion = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        javax.swing.JPanel pnlOpciones = new javax.swing.JPanel();
        javax.swing.JButton btnEditar = new javax.swing.JButton();
        javax.swing.JButton btnEliminar = new javax.swing.JButton();
        javax.swing.JButton btnActualizar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        pnlPromocion = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPromocion = new javax.swing.JTable();
        javax.swing.JPanel pnlOpciones2 = new javax.swing.JPanel();
        javax.swing.JButton btnAñadir = new javax.swing.JButton();
        javax.swing.JButton btnActualizar1 = new javax.swing.JButton();
        pnlReporte = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReporte = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHead.setForeground(new java.awt.Color(102, 102, 255));
        lblHead.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ff9911.png"))); // NOI18N
        lblHead.setText("sdsdsadasdasd");
        getContentPane().add(lblHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 990, 130));

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/administrador (3).png"))); // NOI18N
        jPanel1.add(lblAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 130, 160));

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("TECHSALES");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 230, 40));

        lblNameAdmin.setText("ADMINISTRADOR -CONECTADO");
        jPanel1.add(lblNameAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 190, 20));

        pnlRegi.setBackground(new java.awt.Color(255, 153, 0));
        pnlRegi.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnlRegi.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlRegiMouseMoved(evt);
            }
        });
        pnlRegi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlRegiMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlRegiMouseExited(evt);
            }
        });
        pnlRegi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRegi.setFont(new java.awt.Font("Trebuchet MS", 1, 17)); // NOI18N
        lblRegi.setText("REGISTRAR PRODUCTO");
        pnlRegi.add(lblRegi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 200, 30));

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/documento.png"))); // NOI18N

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pnlRegi.add(panelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 15, 50, 50));

        jPanel1.add(pnlRegi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 300, 80));

        pnlEdit.setBackground(new java.awt.Color(255, 153, 0));
        pnlEdit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnlEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlEditMouseClicked(evt);
            }
        });
        pnlEdit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblElim.setFont(new java.awt.Font("Trebuchet MS", 1, 17)); // NOI18N
        lblElim.setText("EDITAR PRODUCTO");
        pnlEdit.add(lblElim, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 170, 30));

        panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N

        javax.swing.GroupLayout panelImage2Layout = new javax.swing.GroupLayout(panelImage2);
        panelImage2.setLayout(panelImage2Layout);
        panelImage2Layout.setHorizontalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        panelImage2Layout.setVerticalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pnlEdit.add(panelImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 15, 50, 50));

        jPanel1.add(pnlEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 300, 80));

        pnlProm.setBackground(new java.awt.Color(255, 153, 0));
        pnlProm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnlProm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlPromMouseClicked(evt);
            }
        });
        pnlProm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEdit.setFont(new java.awt.Font("Trebuchet MS", 1, 17)); // NOI18N
        lblEdit.setText("PROMOCIÓN");
        pnlProm.add(lblEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 140, 30));

        panelImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/insignia-porcentaje.png"))); // NOI18N

        javax.swing.GroupLayout panelImage3Layout = new javax.swing.GroupLayout(panelImage3);
        panelImage3.setLayout(panelImage3Layout);
        panelImage3Layout.setHorizontalGroup(
            panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        panelImage3Layout.setVerticalGroup(
            panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pnlProm.add(panelImage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 15, 50, 50));

        jPanel1.add(pnlProm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 300, 80));

        pnlRepo.setBackground(new java.awt.Color(255, 153, 0));
        pnlRepo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnlRepo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlRepoMouseClicked(evt);
            }
        });
        pnlRepo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRepo.setFont(new java.awt.Font("Trebuchet MS", 1, 17)); // NOI18N
        lblRepo.setText("REPORTE DE VENTAS");
        pnlRepo.add(lblRepo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 190, 30));

        panelImage4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lista-del-portapapeles.png"))); // NOI18N

        javax.swing.GroupLayout panelImage4Layout = new javax.swing.GroupLayout(panelImage4);
        panelImage4.setLayout(panelImage4Layout);
        panelImage4Layout.setHorizontalGroup(
            panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        panelImage4Layout.setVerticalGroup(
            panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pnlRepo.add(panelImage4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 15, 50, 50));

        jPanel1.add(pnlRepo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 300, 80));

        pnlSalir.setBackground(new java.awt.Color(255, 153, 0));
        pnlSalir.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnlSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlSalirMouseClicked(evt);
            }
        });
        pnlSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 17)); // NOI18N
        jLabel7.setText("SALIR");
        pnlSalir.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 140, 30));

        panelImage5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salida.png"))); // NOI18N

        javax.swing.GroupLayout panelImage5Layout = new javax.swing.GroupLayout(panelImage5);
        panelImage5.setLayout(panelImage5Layout);
        panelImage5Layout.setHorizontalGroup(
            panelImage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );
        panelImage5Layout.setVerticalGroup(
            panelImage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        pnlSalir.add(panelImage5, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 15, 45, 45));

        jPanel1.add(pnlSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 300, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 700));

        pnlRegistro.setBackground(new java.awt.Color(249, 237, 224));

        lblDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDescripcion.setText("Descripción del producto");

        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });

        lblProducto.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblProducto.setText("Tipo de producto");

        lblImagen.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblImagen.setText("Imagen");

        txtPrecU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecUActionPerformed(evt);
            }
        });
        txtPrecU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecUKeyTyped(evt);
            }
        });

        btnRegistrar.setBackground(new java.awt.Color(28, 28, 57));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registro.png"))); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(28, 28, 57));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblPrecio.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblPrecio.setText("Precio unitario");

        chooseFile.setBackground(new java.awt.Color(28, 28, 57));
        chooseFile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chooseFile.setForeground(new java.awt.Color(255, 255, 255));
        chooseFile.setText("Seleccionar archivo");
        chooseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFileActionPerformed(evt);
            }
        });

        lblImage.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblImage.setForeground(new java.awt.Color(153, 153, 153));
        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblMarca.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblMarca.setText("Marca");

        txtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaActionPerformed(evt);
            }
        });

        lblStock.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblStock.setText("Stock");

        txtStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockActionPerformed(evt);
            }
        });
        txtStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStockKeyTyped(evt);
            }
        });

        cboTipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tarjeta gráfica", "Procesador", "Mouse", "Impresora", "Auricular", "Teclado" }));

        javax.swing.GroupLayout pnlRegistroLayout = new javax.swing.GroupLayout(pnlRegistro);
        pnlRegistro.setLayout(pnlRegistroLayout);
        pnlRegistroLayout.setHorizontalGroup(
            pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cboTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPrecU, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                        .addComponent(chooseFile, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                        .addComponent(txtDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                        .addComponent(txtMarca)
                        .addComponent(txtStock)))
                .addGap(180, 180, 180))
            .addGroup(pnlRegistroLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblDescripcion)
                        .addComponent(lblImagen)
                        .addComponent(lblMarca)
                        .addComponent(lblProducto)
                        .addComponent(lblPrecio)
                        .addComponent(lblStock))
                    .addComponent(btnRegistrar))
                .addGap(198, 198, 198)
                .addComponent(btnCancelar)
                .addContainerGap(325, Short.MAX_VALUE))
        );
        pnlRegistroLayout.setVerticalGroup(
            pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcion)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProducto)
                    .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarca)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecio)
                    .addComponent(txtPrecU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStock)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagen)
                    .addComponent(chooseFile, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );

        jTabbedPane1.addTab("Registrar", pnlRegistro);

        pnlEdicion.setBackground(new java.awt.Color(246, 237, 224));

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID DEL PRODUCTO", "DESCRIPCIÓN", "PRECIO UNITARIO"
            }
        ));
        tablaProductos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaProductos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaProductos.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tablaProductos);
        if (tablaProductos.getColumnModel().getColumnCount() > 0) {
            tablaProductos.getColumnModel().getColumn(0).setResizable(false);
            tablaProductos.getColumnModel().getColumn(0).setPreferredWidth(100);
            tablaProductos.getColumnModel().getColumn(1).setResizable(false);
            tablaProductos.getColumnModel().getColumn(1).setPreferredWidth(200);
            tablaProductos.getColumnModel().getColumn(2).setResizable(false);
            tablaProductos.getColumnModel().getColumn(2).setPreferredWidth(100);
        }

        pnlOpciones.setBackground(new java.awt.Color(253, 253, 217));
        pnlOpciones.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Opciones:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        pnlOpciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlOpciones.setOpaque(false);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar_1.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setBorderPainted(false);
        btnEditar.setContentAreaFilled(false);
        btnEditar.addActionListener(evt -> btnEditarActionPerformed());

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar_2.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorderPainted(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.addActionListener(evt -> btnEliminarActionPerformed());

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorderPainted(false);
        btnActualizar.setContentAreaFilled(false);
        btnActualizar.addActionListener(evt -> btnActualizarActionPerformed());

        javax.swing.GroupLayout pnlOpcionesLayout = new javax.swing.GroupLayout(pnlOpciones);
        pnlOpciones.setLayout(pnlOpcionesLayout);
        pnlOpcionesLayout.setHorizontalGroup(
            pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcionesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnEditar)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnActualizar)
                .addContainerGap())
        );
        pnlOpcionesLayout.setVerticalGroup(
            pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcionesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar)
                    .addComponent(btnActualizar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Listado de productos");

        javax.swing.GroupLayout pnlEdicionLayout = new javax.swing.GroupLayout(pnlEdicion);
        pnlEdicion.setLayout(pnlEdicionLayout);
        pnlEdicionLayout.setHorizontalGroup(
            pnlEdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEdicionLayout.createSequentialGroup()
                .addGroup(pnlEdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEdicionLayout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(pnlOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlEdicionLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addGroup(pnlEdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(215, Short.MAX_VALUE))
        );
        pnlEdicionLayout.setVerticalGroup(
            pnlEdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEdicionLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jTabbedPane1.addTab("Editar", pnlEdicion);

        pnlPromocion.setBackground(new java.awt.Color(249, 237, 224));

        tblPromocion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TIPO", "FECHA DE INICIO", "FECHA DE VENCIMIENTO", "DESCUENTO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblPromocion);

        pnlOpciones2.setBackground(new java.awt.Color(253, 253, 217));
        pnlOpciones2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Opciones:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        pnlOpciones2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlOpciones2.setOpaque(false);

        btnAñadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add.png"))); // NOI18N
        btnAñadir.setText("Añadir");
        btnAñadir.setBorderPainted(false);
        btnAñadir.setContentAreaFilled(false);
        btnActualizar.addActionListener(evt -> btnActualizarActionPerformed());
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });

        btnActualizar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        btnActualizar1.setText("Actualizar");
        btnActualizar1.setBorderPainted(false);
        btnActualizar1.setContentAreaFilled(false);
        btnActualizar.addActionListener(evt -> btnActualizarActionPerformed());
        btnActualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlOpciones2Layout = new javax.swing.GroupLayout(pnlOpciones2);
        pnlOpciones2.setLayout(pnlOpciones2Layout);
        pnlOpciones2Layout.setHorizontalGroup(
            pnlOpciones2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpciones2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAñadir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnActualizar1)
                .addGap(19, 19, 19))
        );
        pnlOpciones2Layout.setVerticalGroup(
            pnlOpciones2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOpciones2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlOpciones2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAñadir)
                    .addComponent(btnActualizar1))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlPromocionLayout = new javax.swing.GroupLayout(pnlPromocion);
        pnlPromocion.setLayout(pnlPromocionLayout);
        pnlPromocionLayout.setHorizontalGroup(
            pnlPromocionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPromocionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlOpciones2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(328, 328, 328))
            .addGroup(pnlPromocionLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );
        pnlPromocionLayout.setVerticalGroup(
            pnlPromocionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPromocionLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(pnlOpciones2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Promocion", pnlPromocion);

        pnlReporte.setBackground(new java.awt.Color(249, 237, 224));

        tblReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NOMBRE", "PRODUCTO", "MARCA", "FECHA"
            }
        ));
        tblReporte.setEnabled(false);
        tblReporte.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblReporte);
        if (tblReporte.getColumnModel().getColumnCount() > 0) {
            tblReporte.getColumnModel().getColumn(0).setResizable(false);
            tblReporte.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblReporte.getColumnModel().getColumn(1).setResizable(false);
            tblReporte.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblReporte.getColumnModel().getColumn(2).setResizable(false);
            tblReporte.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblReporte.getColumnModel().getColumn(3).setResizable(false);
            tblReporte.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        txtBuscar.setBackground(new java.awt.Color(252, 252, 217));
        txtBuscar.setBorder(null);
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });

        jLabel5.setText("Buscar:");

        javax.swing.GroupLayout pnlReporteLayout = new javax.swing.GroupLayout(pnlReporte);
        pnlReporte.setLayout(pnlReporteLayout);
        pnlReporteLayout.setHorizontalGroup(
            pnlReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReporteLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(pnlReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlReporteLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlReporteLayout.setVerticalGroup(
            pnlReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReporteLayout.createSequentialGroup()
                .addGap(37, 57, Short.MAX_VALUE)
                .addGroup(pnlReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );

        jTabbedPane1.addTab("Reporte", pnlReporte);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 960, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    void borrarCampos(){
        txtDescripcion.setText("");
        cboTipo.setSelectedIndex(0);
        txtMarca.setText("");
        txtPrecU.setText("");
        txtStock.setText("");
        lblImage.setText("");
    }
    
    public void llenarProductos(){
        ListaProductos.getDataList().clear();
        SqlProductos sqlProd = new SqlProductos();
        sqlProd.ObtenerProducto();
        DefaultTableModel modeloDefault = new DefaultTableModel(new String []{"Producto", "Tipo", "Stock", "Precio unitario"}, ListaProductos.getDataList().size());
        tablaProductos.setModel(modeloDefault);
        TableModel modelDatos = tablaProductos.getModel();
        for (int i = 0; i < ListaProductos.getDataList().size(); i++){
            Producto art = ListaProductos.getDataList().get(i);
            modelDatos.setValueAt(art.getDescripcion(), i, 0);
            modelDatos.setValueAt(art.getTipo(), i, 1);
            modelDatos.setValueAt(art.getStock(), i, 2);
            modelDatos.setValueAt(art.getPrecio(), i, 3);
        } 
        tablaProductos.getTableHeader().setFont(new java.awt.Font("Arial", 0, 14));
        tablaProductos.setFont(new java.awt.Font("Arial", 0, 13));
    }
    
    private void btnEliminarActionPerformed() {                                            
        int selected = tablaProductos.getSelectedRow();
        if (selected == -1)
            JOptionPane.showMessageDialog(null, "Seleccione el producto a eliminar.","Error de eliminación", JOptionPane.WARNING_MESSAGE);
        else{
            int resp = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar este producto?", "Eliminar producto", JOptionPane.YES_NO_OPTION);
            if (resp == 0){
                SqlProductos sqlProd = new SqlProductos();
                sqlProd.eliminarProducto(ListaProductos.getDataList().get(selected).getId_producto());
                llenarProductos();
            }
        }
    }    
    
    private void llenarTablaVentas (){
        modelo = new DefaultTableModel();
        modelo.addColumn("NOMBRE");
        modelo.addColumn("PRODUCTO");
        modelo.addColumn("MARCA");
        modelo.addColumn("FECHA");
        
        obtenerDatosVentas();

        tblReporte.setModel(modelo);
    }
    
    private void llenarTablaPromociones() {
        SqlPromocion prom = new SqlPromocion();
        DefaultTableModel model = new DefaultTableModel();
        List<Promocion> listaProm = prom.obtenerPromociones();
        model.addColumn("ID");
        model.addColumn("TIPO");
        model.addColumn("FECHA DE INICIO");
        model.addColumn("FECHA DE VENCIMIENTO");
        model.addColumn("DESCUENTO");

        model.setRowCount(listaProm.size());

        for (int i = 0; i < listaProm.size(); i++) {
            Promocion p = listaProm.get(i);
            model.setValueAt(p.getIdPromocion(), i, 0);
            model.setValueAt(p.getTipo(), i, 1);
            model.setValueAt(p.getFechaInicio(), i, 2);
            model.setValueAt(p.getFechaFin(), i, 3);
            model.setValueAt(p.getDescuento(), i, 4);
        }
        tblPromocion.setModel(model);
    }
     
    private void btnEditarActionPerformed() {                                          
        int selected = tablaProductos.getSelectedRow();
        if (selected == -1)
            JOptionPane.showMessageDialog(null, "Seleccione el producto a editar.","Error de edición", JOptionPane.WARNING_MESSAGE);
        else{
            EdicionProducto edit = new EdicionProducto();
            edit.generar(tablaProductos.getValueAt(selected, 0).toString(), Integer.parseInt(tablaProductos.getValueAt(selected, 2).toString()),
            Double.parseDouble(tablaProductos.getValueAt(selected, 3).toString()),selected);
            edit.setVisible(true);
            edit.setFrame(this);
            edit.toFront();
        }
    }                                  
    
    private void btnActualizarActionPerformed() {                                              
        llenarProductos();
    }    
        
    private void obtenerDatosVentas(){
        ConexionBD con = new ConexionBD();
        String query = "SELECT c.nombre, c.apellido, p.descripcion, p.marca, v.fecha " +
                "FROM venta v " +
                "JOIN cliente c ON v.id_cliente = c.id_cliente " +
                "JOIN producto p ON v.id_producto = p.id_producto";
        
        try (Connection conn = con.conectar();
             PreparedStatement statement = conn.prepareStatement(query);
             ResultSet resultSet = statement.executeQuery()) {

            while (resultSet.next()) {
                String nombre = resultSet.getString("nombre") + " " + resultSet.getString("apellido");
                String producto = resultSet.getString("descripcion");
                String marca = resultSet.getString("marca");
                String fecha = resultSet.getString("fecha");

                modelo.addRow(new Object[]{nombre, producto, marca, fecha});
            }
            tblReporte.getTableHeader().setFont(new java.awt.Font("Arial", 0, 14));
            tblReporte.setFont(new java.awt.Font("Arial", 0, 13));
        } catch (SQLException e) {
            //Exception
        }
    }
    
    private void pnlRegiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlRegiMouseClicked
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_pnlRegiMouseClicked

    private void pnlRegiMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlRegiMouseMoved
         jTabbedPane1.setBackground(new Color(255,153,102));
    }//GEN-LAST:event_pnlRegiMouseMoved

    private void pnlEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlEditMouseClicked
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_pnlEditMouseClicked

    private void pnlPromMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPromMouseClicked
        llenarTablaPromociones();
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_pnlPromMouseClicked

    private void pnlRepoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlRepoMouseClicked
       jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_pnlRepoMouseClicked

    private void pnlSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSalirMouseClicked
        int resp = JOptionPane.showConfirmDialog(null, "¿Está seguro de salir?");
            if (resp == 0){
                Login log = new Login();
                log.setVisible(true);
                this.dispose();
            }
       
    }//GEN-LAST:event_pnlSalirMouseClicked

    private void pnlRegiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlRegiMouseExited
         jTabbedPane1.setBackground(new Color(255,153,0));   // TODO add your handling code here:
    }//GEN-LAST:event_pnlRegiMouseExited

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void txtPrecUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecUActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try{
            Producto producto = new Producto();
            if (txtDescripcion.getText().isEmpty() || txtMarca.getText().isEmpty() || txtPrecU.getText().isEmpty()
                 || txtStock.getText().isEmpty() || !lblImage.getText().equals("")){
                producto.setDescripcion(txtDescripcion.getText());
                producto.setMarca(txtMarca.getText());
                producto.setTipo(cboTipo.getSelectedItem().toString());
                producto.setPrecio(Integer.parseInt(txtPrecU.getText()));
                producto.setStock(Integer.parseInt(txtStock.getText()));
                if (guardarImagen() != null){
                    String ruta = guardarImagen().replace("\\", "/").substring(3);
                    producto.setImage(ruta);
                    //jTabbedPane1.setSelectedIndex(4);
                    SqlProductos registro = new SqlProductos();
                    registro.registrar(producto);
                    borrarCampos();
                    JOptionPane.showMessageDialog(null,"Producto registrado correctamente.", "Registrado con éxito.", JOptionPane.INFORMATION_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null,"Rellene todos los campos.", "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e){
           JOptionPane.showMessageDialog(null,"Error al registrar producto.\n" + e, "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        borrarCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void chooseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFileActionPerformed
        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.JPG", "jpg");
        fc.setFileFilter(filter);
        int seleccion = fc.showOpenDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION){
            selectedFile = fc.getSelectedFile();
            // Obtener la ruta del archivo
            String filePath = selectedFile.getAbsolutePath();
            lblImage.setText(filePath);
            String fileName = selectedFile.getName();
            String destinationPath = "src/images/productos"; // Especifica la ruta de destino donde quieres guardar la imagen
            destinationFile = new File(destinationPath,fileName);
        }   
    }//GEN-LAST:event_chooseFileActionPerformed

    private void txtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaActionPerformed

    private void txtStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockActionPerformed
    
    TableRowSorter trs;
    
    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        txtBuscar.addKeyListener(new KeyAdapter(){
            @Override
            public void keyReleased(KeyEvent ke){
                trs.setRowFilter(RowFilter.regexFilter("(?i)"+txtBuscar.getText(),0));
            }
        });
        trs = new TableRowSorter(modelo);
        tblReporte.setRowSorter(trs);
    }//GEN-LAST:event_txtBuscarKeyTyped

    private void txtStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockKeyTyped
        char c = evt.getKeyChar();
        if(Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtStockKeyTyped

    private void txtPrecUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecUKeyTyped
        char c = evt.getKeyChar();
        if(Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtPrecUKeyTyped

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        CrearPromociones prom = new CrearPromociones ();
        prom.setVisible(true);
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void btnActualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar1ActionPerformed
        llenarTablaPromociones();
    }//GEN-LAST:event_btnActualizar1ActionPerformed
    
    protected String guardarImagen (){
        try {
            
            java.nio.file.Files.copy(selectedFile.toPath(), destinationFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
            return destinationFile.getPath();

        } catch (IOException e) {
            JOptionPane.showMessageDialog(null,"Error al guardar imagen." + e, "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
        }
        return null;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cboTipo;
    private javax.swing.JButton chooseFile;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblEdit;
    private javax.swing.JLabel lblElim;
    private javax.swing.JLabel lblHead;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblNameAdmin;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblRegi;
    private javax.swing.JLabel lblRepo;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblTitulo;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    private org.edisoncor.gui.panel.PanelImage panelImage3;
    private org.edisoncor.gui.panel.PanelImage panelImage4;
    private org.edisoncor.gui.panel.PanelImage panelImage5;
    private javax.swing.JPanel pnlEdicion;
    private javax.swing.JPanel pnlEdit;
    private javax.swing.JPanel pnlProm;
    private javax.swing.JPanel pnlPromocion;
    private javax.swing.JPanel pnlRegi;
    private javax.swing.JPanel pnlRegistro;
    private javax.swing.JPanel pnlRepo;
    private javax.swing.JPanel pnlReporte;
    private javax.swing.JPanel pnlSalir;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTable tblPromocion;
    private javax.swing.JTable tblReporte;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtPrecU;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
