/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gcs;

import Clases.Producto;
import bdMYSQL.SqlUsers;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;


/**
 *
 * @author usuario
 */
public class Catalogo extends javax.swing.JFrame {
    ArrayList <Producto> art = new ArrayList<>(); 
    org.edisoncor.gui.panel.PanelImage [] paneles = new  org.edisoncor.gui.panel.PanelImage [42];
    javax.swing.JLabel [] labels = new javax.swing.JLabel[42];
        String tipo;

    /**
     * Creates new form Catalogo
     */
    public Catalogo() {
        initComponents();
        llenarMatriz();
        setLocationRelativeTo(null);
        setResizable(false);
    }
    public void SeleccionP (ArrayList <Producto> art, String prod) throws SQLException{
        SqlUsers mod= new SqlUsers();
        int j=0,i=0;
        mod.ObtenerProducto(art);
        Iterator<Producto> itrArt = art.iterator();
        while(itrArt.hasNext()){
            if(art.get(i).getTipo().equals(prod)){
                paneles[j].setIcon(new javax.swing.ImageIcon (getClass().getResource(itrArt.next().getImage())));
                paneles[j].repaint();
                labels[j].setText(art.get(i).getDescripcion());
                j++;
            }
            i++;
        }
    }
    public void BusquedaP (ArrayList <Producto> art, String termino){
        int i=0,j=0;
        Iterator<Producto> itrArt = art.iterator();
        while(itrArt.hasNext()){
            if(art.get(i).getTipo().contains(termino)){
                paneles[i].setIcon(new javax.swing.ImageIcon (getClass().getResource(itrArt.next().getImage())));
                paneles[i].repaint();
                labels[j].setText(art.get(i).getMarca());
                j++;
            }
            i++;
        }   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblBienvenido = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jLabel14 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlCategorias = new javax.swing.JPanel();
        pnlTarjetasG = new javax.swing.JPanel();
        pnlProcesadores = new javax.swing.JPanel();
        pnlMouses = new javax.swing.JPanel();
        pnlImpresoras = new javax.swing.JPanel();
        pnlAuriculares = new javax.swing.JPanel();
        pnlTeclados = new javax.swing.JPanel();
        lblTeclados = new javax.swing.JLabel();
        lblTarjetaG = new javax.swing.JLabel();
        lblProcesador = new javax.swing.JLabel();
        lblMouse = new javax.swing.JLabel();
        lblImpresora = new javax.swing.JLabel();
        lblAuricular = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pnlPestañaP1 = new javax.swing.JPanel();
        imProducto1 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto1 = new javax.swing.JLabel();
        imProducto2 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto2 = new javax.swing.JLabel();
        imProducto3 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto3 = new javax.swing.JLabel();
        imProducto4 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto4 = new javax.swing.JLabel();
        imProducto5 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto5 = new javax.swing.JLabel();
        imProducto6 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto6 = new javax.swing.JLabel();
        btnSiguiente1 = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        pnlPestañaP2 = new javax.swing.JPanel();
        imProducto7 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto7 = new javax.swing.JLabel();
        imProducto8 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto8 = new javax.swing.JLabel();
        imProducto9 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto9 = new javax.swing.JLabel();
        imProducto10 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto10 = new javax.swing.JLabel();
        imProducto11 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto11 = new javax.swing.JLabel();
        imProducto12 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto12 = new javax.swing.JLabel();
        btnSiguiente2 = new javax.swing.JButton();
        pnlPestañaP3 = new javax.swing.JPanel();
        imProducto13 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto13 = new javax.swing.JLabel();
        imProducto14 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto14 = new javax.swing.JLabel();
        imProducto15 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto15 = new javax.swing.JLabel();
        imProducto16 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto16 = new javax.swing.JLabel();
        imProducto17 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto17 = new javax.swing.JLabel();
        imProducto18 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto18 = new javax.swing.JLabel();
        btnSiguiente3 = new javax.swing.JButton();
        pnlPestañaP4 = new javax.swing.JPanel();
        imProducto19 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto19 = new javax.swing.JLabel();
        imProducto20 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto20 = new javax.swing.JLabel();
        imProducto21 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto21 = new javax.swing.JLabel();
        imProducto22 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto22 = new javax.swing.JLabel();
        imProducto23 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto23 = new javax.swing.JLabel();
        imProducto24 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto24 = new javax.swing.JLabel();
        btnSiguiente4 = new javax.swing.JButton();
        pnlPestañaP5 = new javax.swing.JPanel();
        imProducto25 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto25 = new javax.swing.JLabel();
        imProducto26 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto26 = new javax.swing.JLabel();
        imProducto27 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto27 = new javax.swing.JLabel();
        imProducto28 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto28 = new javax.swing.JLabel();
        imProducto29 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto29 = new javax.swing.JLabel();
        imProducto30 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto30 = new javax.swing.JLabel();
        btnSiguiente5 = new javax.swing.JButton();
        pnlPestañaP6 = new javax.swing.JPanel();
        imProducto31 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto31 = new javax.swing.JLabel();
        imProducto32 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto32 = new javax.swing.JLabel();
        imProducto33 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto33 = new javax.swing.JLabel();
        imProducto34 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto34 = new javax.swing.JLabel();
        imProducto35 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto35 = new javax.swing.JLabel();
        imProducto36 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto36 = new javax.swing.JLabel();
        btnSiguiente6 = new javax.swing.JButton();
        pnlPestañaP7 = new javax.swing.JPanel();
        imProducto37 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto37 = new javax.swing.JLabel();
        imProducto38 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto38 = new javax.swing.JLabel();
        imProducto39 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto39 = new javax.swing.JLabel();
        imProducto40 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto40 = new javax.swing.JLabel();
        imProducto41 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto41 = new javax.swing.JLabel();
        imProducto42 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto42 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblName.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("TECHSALES");
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 230, 40));

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 153, 0));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/categorizacion.png"))); // NOI18N
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 60));

        jLabel49.setBackground(new java.awt.Color(255, 255, 255));
        jLabel49.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("CATEGORÍAS");
        jPanel7.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 110, 30));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 300, 80));

        jPanel8.setBackground(new java.awt.Color(255, 153, 0));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bolsa-de-la-compra.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("MIS COMPRAS");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 120, 30));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 300, 80));

        jPanel9.setBackground(new java.awt.Color(255, 153, 0));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
        });
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carrito-de-compras (1).png"))); // NOI18N
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 70));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CARRITO");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 110, 30));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 300, 80));

        jPanel10.setBackground(new java.awt.Color(255, 153, 0));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
        });
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        jLabel9.setToolTipText("");
        jPanel10.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 70));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SALIR");
        jPanel10.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 110, 30));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 300, 80));

        lblBienvenido.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblBienvenido.setForeground(new java.awt.Color(235, 235, 235));
        lblBienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBienvenido.setText("BIENVENIDO");
        jPanel1.add(lblBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 120, 40));

        lblNombre.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(235, 235, 235));
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 220, 40));

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SOLOiconEmpresa.png"))); // NOI18N
        jPanel1.add(panelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 45, 65, 65));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 700));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ff9911.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 990, 120));

        pnlCategorias.setBackground(new java.awt.Color(255, 255, 255));
        pnlCategorias.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTarjetasG.setBackground(new java.awt.Color(255, 255, 255));
        pnlTarjetasG.setOpaque(false);
        pnlTarjetasG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTarjetasGMouseClicked(evt);
            }
        });
        pnlTarjetasG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlCategorias.add(pnlTarjetasG, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 200, 220));

        pnlProcesadores.setBackground(new java.awt.Color(255, 255, 255));
        pnlProcesadores.setOpaque(false);
        pnlProcesadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlProcesadoresMouseClicked(evt);
            }
        });
        pnlProcesadores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlCategorias.add(pnlProcesadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 200, 220));

        pnlMouses.setBackground(new java.awt.Color(255, 255, 255));
        pnlMouses.setOpaque(false);
        pnlMouses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMousesMouseClicked(evt);
            }
        });
        pnlMouses.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlCategorias.add(pnlMouses, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, 190, 230));

        pnlImpresoras.setBackground(new java.awt.Color(255, 255, 255));
        pnlImpresoras.setOpaque(false);
        pnlImpresoras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlImpresorasMouseClicked(evt);
            }
        });
        pnlImpresoras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlCategorias.add(pnlImpresoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 210, 240));

        pnlAuriculares.setBackground(new java.awt.Color(255, 255, 255));
        pnlAuriculares.setOpaque(false);
        pnlAuriculares.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAuricularesMouseClicked(evt);
            }
        });
        pnlAuriculares.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlCategorias.add(pnlAuriculares, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 210, 240));

        pnlTeclados.setBackground(new java.awt.Color(255, 255, 255));
        pnlTeclados.setOpaque(false);
        pnlTeclados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTecladosMouseClicked(evt);
            }
        });
        pnlTeclados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlCategorias.add(pnlTeclados, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 180, 210));

        lblTeclados.setBackground(new java.awt.Color(0, 0, 0));
        lblTeclados.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblTeclados.setForeground(new java.awt.Color(0, 0, 0));
        lblTeclados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTeclados.setText("TECLADOS");
        pnlCategorias.add(lblTeclados, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, 120, 30));

        lblTarjetaG.setBackground(new java.awt.Color(0, 0, 0));
        lblTarjetaG.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblTarjetaG.setForeground(new java.awt.Color(0, 0, 0));
        lblTarjetaG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTarjetaG.setText("TARJETAS GRÁFICAS");
        pnlCategorias.add(lblTarjetaG, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 180, 30));

        lblProcesador.setBackground(new java.awt.Color(0, 0, 0));
        lblProcesador.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProcesador.setForeground(new java.awt.Color(0, 0, 0));
        lblProcesador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProcesador.setText("PROCESADORES");
        pnlCategorias.add(lblProcesador, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 140, 30));

        lblMouse.setBackground(new java.awt.Color(0, 0, 0));
        lblMouse.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblMouse.setForeground(new java.awt.Color(0, 0, 0));
        lblMouse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMouse.setText("MOUSE");
        pnlCategorias.add(lblMouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, 120, 30));

        lblImpresora.setBackground(new java.awt.Color(0, 0, 0));
        lblImpresora.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblImpresora.setForeground(new java.awt.Color(0, 0, 0));
        lblImpresora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImpresora.setText("IMPRESORAS");
        pnlCategorias.add(lblImpresora, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 120, 30));

        lblAuricular.setBackground(new java.awt.Color(0, 0, 0));
        lblAuricular.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblAuricular.setForeground(new java.awt.Color(0, 0, 0));
        lblAuricular.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAuricular.setText("AURICULARES");
        pnlCategorias.add(lblAuricular, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, 140, 30));

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/asus.jpg"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        pnlCategorias.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 180, -1));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/intel-core-i5165172.jpg"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        pnlCategorias.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 180, 190));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mouse/m3.jpg"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        pnlCategorias.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 140, -1));

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/impresora-epson-ecotank-l3210-multifuncional-pnc11cj68303-.jpg"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        pnlCategorias.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 180, -1));

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/auriculares.jpg"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        pnlCategorias.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 180, -1));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/teclado/te1.jpg"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        pnlCategorias.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, 160, 160));

        jTabbedPane1.addTab("Categorias", pnlCategorias);

        pnlPestañaP1.setBackground(new java.awt.Color(255, 255, 255));
        pnlPestañaP1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imProducto1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP1.add(imProducto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 180, 180));

        lblProducto1.setBackground(new java.awt.Color(255, 255, 255));
        lblProducto1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP1.add(lblProducto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 240, 30));

        imProducto2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP1.add(imProducto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 180, 180));

        lblProducto2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP1.add(lblProducto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 220, 30));

        imProducto3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP1.add(imProducto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, 180, 180));

        lblProducto3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP1.add(lblProducto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 260, 30));

        imProducto4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP1.add(imProducto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 180, 180));

        lblProducto4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP1.add(lblProducto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 240, 30));

        imProducto5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP1.add(imProducto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 180, 180));

        lblProducto5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP1.add(lblProducto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, 240, 30));

        imProducto6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP1.add(imProducto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 180, 180));

        lblProducto6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP1.add(lblProducto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 490, 260, 30));

        btnSiguiente1.setBackground(new java.awt.Color(255, 153, 0));
        btnSiguiente1.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        btnSiguiente1.setText("SIGUIENTE");
        btnSiguiente1.setBorder(null);
        btnSiguiente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguiente1ActionPerformed(evt);
            }
        });
        pnlPestañaP1.add(btnSiguiente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 400, 70, 60));

        txtBuscar.setBackground(new java.awt.Color(204, 204, 204));
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });
        pnlPestañaP1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 330, -1));

        jTabbedPane1.addTab("Productos 1", pnlPestañaP1);

        pnlPestañaP2.setBackground(new java.awt.Color(255, 255, 255));
        pnlPestañaP2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imProducto7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP2.add(imProducto7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 180, 180));

        lblProducto7.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP2.add(lblProducto7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 240, 30));

        imProducto8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP2.add(imProducto8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 180, 180));

        lblProducto8.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP2.add(lblProducto8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 220, 30));

        imProducto9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP2.add(imProducto9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 180, 180));

        lblProducto9.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP2.add(lblProducto9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 260, 30));

        imProducto10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP2.add(imProducto10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 180, 180));

        lblProducto10.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP2.add(lblProducto10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 240, 30));

        imProducto11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP2.add(imProducto11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 180, 180));

        lblProducto11.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP2.add(lblProducto11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 240, 30));

        imProducto12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP2.add(imProducto12, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, 180, 180));

        lblProducto12.setBackground(new java.awt.Color(51, 51, 51));
        lblProducto12.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP2.add(lblProducto12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, 260, 30));

        btnSiguiente2.setBackground(new java.awt.Color(255, 153, 0));
        btnSiguiente2.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        btnSiguiente2.setText("SIGUIENTE");
        btnSiguiente2.setBorder(null);
        btnSiguiente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguiente2ActionPerformed(evt);
            }
        });
        pnlPestañaP2.add(btnSiguiente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 400, 70, 60));

        jTabbedPane1.addTab("Productos 2", pnlPestañaP2);

        pnlPestañaP3.setBackground(new java.awt.Color(255, 255, 255));
        pnlPestañaP3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imProducto13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP3.add(imProducto13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 180, 180));

        lblProducto13.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP3.add(lblProducto13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 240, 30));

        imProducto14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP3.add(imProducto14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 180, 180));

        lblProducto14.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP3.add(lblProducto14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 240, 30));

        imProducto15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP3.add(imProducto15, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 180, 180));

        lblProducto15.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP3.add(lblProducto15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 220, 30));

        imProducto16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP3.add(imProducto16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 180, 180));

        lblProducto16.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP3.add(lblProducto16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 240, 30));

        imProducto17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP3.add(imProducto17, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 180, 180));

        lblProducto17.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP3.add(lblProducto17, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 260, 30));

        imProducto18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP3.add(imProducto18, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, 180, 180));

        lblProducto18.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP3.add(lblProducto18, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, 260, 30));

        btnSiguiente3.setBackground(new java.awt.Color(255, 153, 0));
        btnSiguiente3.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        btnSiguiente3.setText("SIGUIENTE");
        btnSiguiente3.setBorder(null);
        btnSiguiente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguiente3ActionPerformed(evt);
            }
        });
        pnlPestañaP3.add(btnSiguiente3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 400, 70, 60));

        jTabbedPane1.addTab("Productos 3", pnlPestañaP3);

        pnlPestañaP4.setBackground(new java.awt.Color(255, 255, 255));
        pnlPestañaP4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imProducto19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP4.add(imProducto19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 180, 180));

        lblProducto19.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP4.add(lblProducto19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 240, 30));

        imProducto20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP4.add(imProducto20, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 180, 180));

        lblProducto20.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP4.add(lblProducto20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 240, 30));

        imProducto21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP4.add(imProducto21, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 180, 180));

        lblProducto21.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP4.add(lblProducto21, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 220, 30));

        imProducto22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP4.add(imProducto22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 180, 180));

        lblProducto22.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP4.add(lblProducto22, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 240, 30));

        imProducto23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP4.add(imProducto23, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 180, 180));

        lblProducto23.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP4.add(lblProducto23, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 260, 30));

        imProducto24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP4.add(imProducto24, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, 180, 180));

        lblProducto24.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP4.add(lblProducto24, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, 260, 30));

        btnSiguiente4.setBackground(new java.awt.Color(255, 153, 0));
        btnSiguiente4.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        btnSiguiente4.setText("SIGUIENTE");
        btnSiguiente4.setBorder(null);
        btnSiguiente4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguiente4ActionPerformed(evt);
            }
        });
        pnlPestañaP4.add(btnSiguiente4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 400, 70, 60));

        jTabbedPane1.addTab("Productos 4", pnlPestañaP4);

        pnlPestañaP5.setBackground(new java.awt.Color(255, 255, 255));
        pnlPestañaP5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imProducto25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP5.add(imProducto25, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 180, 180));

        lblProducto25.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP5.add(lblProducto25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 240, 30));

        imProducto26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP5.add(imProducto26, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 180, 180));

        lblProducto26.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP5.add(lblProducto26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 240, 30));

        imProducto27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP5.add(imProducto27, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 180, 180));

        lblProducto27.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP5.add(lblProducto27, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 220, 30));

        imProducto28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP5.add(imProducto28, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 180, 180));

        lblProducto28.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP5.add(lblProducto28, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 240, 30));

        imProducto29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP5.add(imProducto29, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 180, 180));

        lblProducto29.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP5.add(lblProducto29, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 260, 30));

        imProducto30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP5.add(imProducto30, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, 180, 180));

        lblProducto30.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP5.add(lblProducto30, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, 260, 30));

        btnSiguiente5.setBackground(new java.awt.Color(255, 153, 0));
        btnSiguiente5.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        btnSiguiente5.setText("SIGUIENTE");
        btnSiguiente5.setBorder(null);
        btnSiguiente5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguiente5ActionPerformed(evt);
            }
        });
        pnlPestañaP5.add(btnSiguiente5, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 400, 70, 60));

        jTabbedPane1.addTab("Productos 5", pnlPestañaP5);

        pnlPestañaP6.setBackground(new java.awt.Color(255, 255, 255));
        pnlPestañaP6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imProducto31.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP6.add(imProducto31, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 180, 180));

        lblProducto31.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP6.add(lblProducto31, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 240, 30));

        imProducto32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP6.add(imProducto32, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 180, 180));

        lblProducto32.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP6.add(lblProducto32, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 240, 30));

        imProducto33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP6.add(imProducto33, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 180, 180));

        lblProducto33.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP6.add(lblProducto33, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 220, 30));

        imProducto34.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP6.add(imProducto34, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 180, 180));

        lblProducto34.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP6.add(lblProducto34, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 240, 30));

        imProducto35.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP6.add(imProducto35, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 180, 180));

        lblProducto35.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP6.add(lblProducto35, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 260, 30));

        imProducto36.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP6.add(imProducto36, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, 180, 180));

        lblProducto36.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP6.add(lblProducto36, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, 260, 30));

        btnSiguiente6.setBackground(new java.awt.Color(255, 153, 0));
        btnSiguiente6.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        btnSiguiente6.setText("SIGUIENTE");
        btnSiguiente6.setBorder(null);
        btnSiguiente6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguiente6ActionPerformed(evt);
            }
        });
        pnlPestañaP6.add(btnSiguiente6, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 400, 70, 60));

        jTabbedPane1.addTab("Productos 6", pnlPestañaP6);

        pnlPestañaP7.setBackground(new java.awt.Color(255, 255, 255));
        pnlPestañaP7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imProducto37.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP7.add(imProducto37, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 180, 180));

        lblProducto37.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP7.add(lblProducto37, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 240, 30));

        imProducto38.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP7.add(imProducto38, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 180, 180));

        lblProducto38.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP7.add(lblProducto38, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 220, 30));

        imProducto39.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP7.add(imProducto39, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 180, 180));

        lblProducto39.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP7.add(lblProducto39, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 260, 30));

        imProducto40.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP7.add(imProducto40, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 180, 180));

        lblProducto40.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP7.add(lblProducto40, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 240, 30));

        imProducto41.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP7.add(imProducto41, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 180, 180));

        lblProducto41.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP7.add(lblProducto41, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 240, 30));

        imProducto42.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPestañaP7.add(imProducto42, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, 180, 180));

        lblProducto42.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPestañaP7.add(lblProducto42, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, 260, 30));

        jTabbedPane1.addTab("Productos 7", pnlPestañaP7);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 990, 580));
        jTabbedPane1.getAccessibleContext().setAccessibleName("tab3");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void llenarMatriz(){
        paneles [0] = imProducto1;
        paneles [1] = imProducto2;
        paneles [2] = imProducto3;
        paneles [3] = imProducto4;
        paneles [4] = imProducto5;
        paneles [5] = imProducto6;
        paneles [6] = imProducto7;
        paneles [7] = imProducto8;
        paneles [8] = imProducto9;
        paneles [9] = imProducto10;
        paneles [10] = imProducto11;
        paneles [11] = imProducto12;
        paneles [12] = imProducto13;
        paneles [13] = imProducto7;
        paneles [14] = imProducto9;
        paneles [15] = imProducto10;
        paneles [16] = imProducto11;
        paneles [17] = imProducto12;
        paneles [18] = imProducto19;
        paneles [19] = imProducto20;
        paneles [20] = imProducto21;
        paneles [21] = imProducto22;
        paneles [22] = imProducto23;
        paneles [23] = imProducto24;
        paneles [24] = imProducto25;
        paneles [25] = imProducto26;
        paneles [26] = imProducto27;
        paneles [27] = imProducto28;
        paneles [28] = imProducto29;
        paneles [29] = imProducto30;
        paneles [30] = imProducto31;
        paneles [31] = imProducto32;
        paneles [32] = imProducto33;
        paneles [33] = imProducto34;
        paneles [34] = imProducto35;
        paneles [35] = imProducto36;
        paneles [36] = imProducto37;
        paneles [37] = imProducto38;
        paneles [38] = imProducto39;
        paneles [39] = imProducto40;
        paneles [40] = imProducto41;
        paneles [41] = imProducto42;
        labels [0] = lblProducto1;
        labels [1] = lblProducto2;
        labels [2] = lblProducto3;
        labels [3] = lblProducto4;
        labels [4] = lblProducto5;
        labels [5] = lblProducto6;
        labels [6] = lblProducto7;
        labels [7] = lblProducto8;
        labels [8] = lblProducto9;
        labels [9] = lblProducto10;
        labels [10] = lblProducto11;
        labels [11] = lblProducto12;
        labels [12] = lblProducto13;
        labels [13] = lblProducto14;
        labels [14] = lblProducto15;
        labels [15] = lblProducto16;
        labels [16] = lblProducto17;
        labels [17] = lblProducto18;
        labels [18] = lblProducto19;
        labels [19] = lblProducto20;
        labels [20] = lblProducto21;
        labels [21] = lblProducto22;
        labels [22] = lblProducto23;
        labels [23] = lblProducto24;
        labels [24] = lblProducto25;
        labels [25] = lblProducto26;
        labels [26] = lblProducto27;
        labels [27] = lblProducto28;
        labels [28] = lblProducto29;
        labels [29] = lblProducto30;
        labels [30] = lblProducto31;
        labels [31] = lblProducto32;
        labels [32] = lblProducto33;
        labels [33] = lblProducto34;
        labels [34] = lblProducto35;
        labels [35] = lblProducto36;
        labels [36] = lblProducto37;
        labels [37] = lblProducto38;
        labels [38] = lblProducto39;
        labels [39] = lblProducto40;
        labels [40] = lblProducto41;
        labels [41] = lblProducto42;
    }
    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
            System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel10MouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void btnSiguiente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguiente2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3); 
    }//GEN-LAST:event_btnSiguiente2ActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnSiguiente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguiente1ActionPerformed
        jTabbedPane1.setSelectedIndex(2);        // TODO add your handling code here:
    }//GEN-LAST:event_btnSiguiente1ActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    private void pnlProcesadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlProcesadoresMouseClicked
        // TODO add your handling code here:
        tipo = lblProcesador.getText();
        try {
            SeleccionP(art,tipo);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al obtener los productos.");
        }
        jTabbedPane1.setSelectedIndex(1);      
    }//GEN-LAST:event_pnlProcesadoresMouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    private void btnSiguiente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguiente3ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(4); 
    }//GEN-LAST:event_btnSiguiente3ActionPerformed

    private void btnSiguiente4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguiente4ActionPerformed
        jTabbedPane1.setSelectedIndex(5);
    }//GEN-LAST:event_btnSiguiente4ActionPerformed

    private void btnSiguiente5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguiente5ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(6); 
    }//GEN-LAST:event_btnSiguiente5ActionPerformed

    private void btnSiguiente6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguiente6ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(7); 
    }//GEN-LAST:event_btnSiguiente6ActionPerformed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17MouseClicked

    private void pnlTarjetasGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTarjetasGMouseClicked
        // TODO add your handling code here:
        tipo = lblTarjetaG.getText();
        try {
            SeleccionP(art,tipo);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al obtener los productos.");
        }
        jTabbedPane1.setSelectedIndex(1);
        
    }//GEN-LAST:event_pnlTarjetasGMouseClicked

    private void pnlImpresorasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlImpresorasMouseClicked
        // TODO add your handling code here:
        tipo = lblImpresora.getText();
        try {
            SeleccionP(art,tipo);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al obtener los productos.");
        }
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_pnlImpresorasMouseClicked

    private void pnlMousesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMousesMouseClicked
        // TODO add your handling code here:
        tipo = lblMouse.getText();
        try {
            SeleccionP(art,tipo);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al obtener los productos.");
        }
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_pnlMousesMouseClicked

    private void pnlAuricularesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAuricularesMouseClicked
        // TODO add your handling code here:
        tipo = lblAuricular.getText();
        try {
            SeleccionP(art,tipo);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al obtener los productos.");
        }
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_pnlAuricularesMouseClicked

    private void pnlTecladosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTecladosMouseClicked
        // TODO add your handling code here:
        tipo = lblTeclados.getText();
        try {
            SeleccionP(art,tipo);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al obtener los productos.");
        }
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_pnlTecladosMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked

 Carrito obj = new Carrito();
     obj.setVisible(true);
      this.setVisible(false);
      this.setResizable(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
       Carrito obj = new Carrito();
      obj.setVisible(true);
      this.setVisible(false);
      this.setResizable(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel9MouseClicked

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        // TODO add your handling code here:
        String termino;
        termino = txtBuscar.getText();
        BusquedaP(art,termino);
        
    }//GEN-LAST:event_txtBuscarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Catalogo().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente1;
    private javax.swing.JButton btnSiguiente2;
    private javax.swing.JButton btnSiguiente3;
    private javax.swing.JButton btnSiguiente4;
    private javax.swing.JButton btnSiguiente5;
    private javax.swing.JButton btnSiguiente6;
    private org.edisoncor.gui.panel.PanelImage imProducto1;
    private org.edisoncor.gui.panel.PanelImage imProducto10;
    private org.edisoncor.gui.panel.PanelImage imProducto11;
    private org.edisoncor.gui.panel.PanelImage imProducto12;
    private org.edisoncor.gui.panel.PanelImage imProducto13;
    private org.edisoncor.gui.panel.PanelImage imProducto14;
    private org.edisoncor.gui.panel.PanelImage imProducto15;
    private org.edisoncor.gui.panel.PanelImage imProducto16;
    private org.edisoncor.gui.panel.PanelImage imProducto17;
    private org.edisoncor.gui.panel.PanelImage imProducto18;
    private org.edisoncor.gui.panel.PanelImage imProducto19;
    private org.edisoncor.gui.panel.PanelImage imProducto2;
    private org.edisoncor.gui.panel.PanelImage imProducto20;
    private org.edisoncor.gui.panel.PanelImage imProducto21;
    private org.edisoncor.gui.panel.PanelImage imProducto22;
    private org.edisoncor.gui.panel.PanelImage imProducto23;
    private org.edisoncor.gui.panel.PanelImage imProducto24;
    private org.edisoncor.gui.panel.PanelImage imProducto25;
    private org.edisoncor.gui.panel.PanelImage imProducto26;
    private org.edisoncor.gui.panel.PanelImage imProducto27;
    private org.edisoncor.gui.panel.PanelImage imProducto28;
    private org.edisoncor.gui.panel.PanelImage imProducto29;
    private org.edisoncor.gui.panel.PanelImage imProducto3;
    private org.edisoncor.gui.panel.PanelImage imProducto30;
    private org.edisoncor.gui.panel.PanelImage imProducto31;
    private org.edisoncor.gui.panel.PanelImage imProducto32;
    private org.edisoncor.gui.panel.PanelImage imProducto33;
    private org.edisoncor.gui.panel.PanelImage imProducto34;
    private org.edisoncor.gui.panel.PanelImage imProducto35;
    private org.edisoncor.gui.panel.PanelImage imProducto36;
    private org.edisoncor.gui.panel.PanelImage imProducto37;
    private org.edisoncor.gui.panel.PanelImage imProducto38;
    private org.edisoncor.gui.panel.PanelImage imProducto39;
    private org.edisoncor.gui.panel.PanelImage imProducto4;
    private org.edisoncor.gui.panel.PanelImage imProducto40;
    private org.edisoncor.gui.panel.PanelImage imProducto41;
    private org.edisoncor.gui.panel.PanelImage imProducto42;
    private org.edisoncor.gui.panel.PanelImage imProducto5;
    private org.edisoncor.gui.panel.PanelImage imProducto6;
    private org.edisoncor.gui.panel.PanelImage imProducto7;
    private org.edisoncor.gui.panel.PanelImage imProducto8;
    private org.edisoncor.gui.panel.PanelImage imProducto9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAuricular;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblImpresora;
    private javax.swing.JLabel lblMouse;
    private javax.swing.JLabel lblName;
    public javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblProcesador;
    private javax.swing.JLabel lblProducto1;
    private javax.swing.JLabel lblProducto10;
    private javax.swing.JLabel lblProducto11;
    private javax.swing.JLabel lblProducto12;
    private javax.swing.JLabel lblProducto13;
    private javax.swing.JLabel lblProducto14;
    private javax.swing.JLabel lblProducto15;
    private javax.swing.JLabel lblProducto16;
    private javax.swing.JLabel lblProducto17;
    private javax.swing.JLabel lblProducto18;
    private javax.swing.JLabel lblProducto19;
    private javax.swing.JLabel lblProducto2;
    private javax.swing.JLabel lblProducto20;
    private javax.swing.JLabel lblProducto21;
    private javax.swing.JLabel lblProducto22;
    private javax.swing.JLabel lblProducto23;
    private javax.swing.JLabel lblProducto24;
    private javax.swing.JLabel lblProducto25;
    private javax.swing.JLabel lblProducto26;
    private javax.swing.JLabel lblProducto27;
    private javax.swing.JLabel lblProducto28;
    private javax.swing.JLabel lblProducto29;
    private javax.swing.JLabel lblProducto3;
    private javax.swing.JLabel lblProducto30;
    private javax.swing.JLabel lblProducto31;
    private javax.swing.JLabel lblProducto32;
    private javax.swing.JLabel lblProducto33;
    private javax.swing.JLabel lblProducto34;
    private javax.swing.JLabel lblProducto35;
    private javax.swing.JLabel lblProducto36;
    private javax.swing.JLabel lblProducto37;
    private javax.swing.JLabel lblProducto38;
    private javax.swing.JLabel lblProducto39;
    private javax.swing.JLabel lblProducto4;
    private javax.swing.JLabel lblProducto40;
    private javax.swing.JLabel lblProducto41;
    private javax.swing.JLabel lblProducto42;
    private javax.swing.JLabel lblProducto5;
    private javax.swing.JLabel lblProducto6;
    private javax.swing.JLabel lblProducto7;
    private javax.swing.JLabel lblProducto8;
    private javax.swing.JLabel lblProducto9;
    private javax.swing.JLabel lblTarjetaG;
    private javax.swing.JLabel lblTeclados;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private javax.swing.JPanel pnlAuriculares;
    private javax.swing.JPanel pnlCategorias;
    private javax.swing.JPanel pnlImpresoras;
    private javax.swing.JPanel pnlMouses;
    private javax.swing.JPanel pnlPestañaP1;
    private javax.swing.JPanel pnlPestañaP2;
    private javax.swing.JPanel pnlPestañaP3;
    private javax.swing.JPanel pnlPestañaP4;
    private javax.swing.JPanel pnlPestañaP5;
    private javax.swing.JPanel pnlPestañaP6;
    private javax.swing.JPanel pnlPestañaP7;
    private javax.swing.JPanel pnlProcesadores;
    private javax.swing.JPanel pnlTarjetasG;
    private javax.swing.JPanel pnlTeclados;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
