/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gcs;

/**
 *
 * @author usuario
 */
public class Catalogo extends javax.swing.JFrame {

    /**
     * Creates new form Catalogo
     */
    public Catalogo() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        pnlProducto1 = new javax.swing.JPanel();
        pnlProducto2 = new javax.swing.JPanel();
        pnlProducto3 = new javax.swing.JPanel();
        pnlProducto4 = new javax.swing.JPanel();
        pnlProducto5 = new javax.swing.JPanel();
        pnlProducto6 = new javax.swing.JPanel();
        lblProducto1 = new javax.swing.JLabel();
        lblProducto2 = new javax.swing.JLabel();
        lblProducto3 = new javax.swing.JLabel();
        lblProducto4 = new javax.swing.JLabel();
        lblProducto5 = new javax.swing.JLabel();
        lblProducto6 = new javax.swing.JLabel();
        btnSiguiente1 = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jPanel21 = new javax.swing.JPanel();
        pnlProducto7 = new javax.swing.JPanel();
        lblProducto7 = new javax.swing.JLabel();
        pnlProducto8 = new javax.swing.JPanel();
        lblProducto8 = new javax.swing.JLabel();
        pnlProducto9 = new javax.swing.JPanel();
        lblProducto9 = new javax.swing.JLabel();
        pnlProducto10 = new javax.swing.JPanel();
        lblProducto10 = new javax.swing.JLabel();
        pnlProducto11 = new javax.swing.JPanel();
        lblProducto11 = new javax.swing.JLabel();
        pnlProducto12 = new javax.swing.JPanel();
        lblProducto12 = new javax.swing.JLabel();
        btnSiguiente2 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        pnlProducto13 = new javax.swing.JPanel();
        lblProducto13 = new javax.swing.JLabel();
        pnlProducto14 = new javax.swing.JPanel();
        lblProducto14 = new javax.swing.JLabel();
        pnlProducto15 = new javax.swing.JPanel();
        lblProducto15 = new javax.swing.JLabel();
        pnlProducto16 = new javax.swing.JPanel();
        lblProducto16 = new javax.swing.JLabel();
        pnlProducto17 = new javax.swing.JPanel();
        lblProducto17 = new javax.swing.JLabel();
        pnlProducto18 = new javax.swing.JPanel();
        lblProducto18 = new javax.swing.JLabel();
        btnSiguiente3 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        pnlProducto19 = new javax.swing.JPanel();
        lblProducto19 = new javax.swing.JLabel();
        pnlProducto20 = new javax.swing.JPanel();
        lblProducto20 = new javax.swing.JLabel();
        pnlProducto21 = new javax.swing.JPanel();
        lblProducto21 = new javax.swing.JLabel();
        pnlProducto22 = new javax.swing.JPanel();
        lblProducto22 = new javax.swing.JLabel();
        pnlProducto23 = new javax.swing.JPanel();
        lblProducto23 = new javax.swing.JLabel();
        pnlProducto24 = new javax.swing.JPanel();
        lblProducto24 = new javax.swing.JLabel();
        btnSiguiente4 = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        pnlProducto25 = new javax.swing.JPanel();
        lblProducto25 = new javax.swing.JLabel();
        pnlProducto26 = new javax.swing.JPanel();
        lblProducto26 = new javax.swing.JLabel();
        pnlProducto27 = new javax.swing.JPanel();
        lblProducto27 = new javax.swing.JLabel();
        pnlProducto28 = new javax.swing.JPanel();
        lblProducto28 = new javax.swing.JLabel();
        pnlProducto29 = new javax.swing.JPanel();
        lblProducto29 = new javax.swing.JLabel();
        pnlProducto30 = new javax.swing.JPanel();
        lblProducto30 = new javax.swing.JLabel();
        btnSiguiente5 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        pnlProducto31 = new javax.swing.JPanel();
        lblProducto31 = new javax.swing.JLabel();
        pnlProducto32 = new javax.swing.JPanel();
        lblProducto32 = new javax.swing.JLabel();
        pnlProducto33 = new javax.swing.JPanel();
        lblProducto33 = new javax.swing.JLabel();
        pnlProducto34 = new javax.swing.JPanel();
        lblProducto34 = new javax.swing.JLabel();
        pnlProducto35 = new javax.swing.JPanel();
        lblProducto35 = new javax.swing.JLabel();
        pnlProducto36 = new javax.swing.JPanel();
        lblProducto36 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/grupo-de-usuarios.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 140, 150));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("BIENVENIDO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 70, 40));

        jPanel7.setBackground(new java.awt.Color(255, 153, 0));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/categorizacion.png"))); // NOI18N
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 60));

        jLabel49.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel49.setText("CATEGORÍAS");
        jPanel7.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 110, 30));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 300, 80));

        jPanel8.setBackground(new java.awt.Color(255, 153, 0));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bolsa-de-la-compra.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, -1));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel8.setText("MIS COMPRAS");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 120, 30));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 300, 80));

        jPanel9.setBackground(new java.awt.Color(255, 153, 0));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carrito-de-compras (1).png"))); // NOI18N
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 70));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel10.setText("CARRITO");
        jPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 110, 30));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 300, 80));

        jPanel10.setBackground(new java.awt.Color(255, 153, 0));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
        });
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        jLabel9.setToolTipText("");
        jPanel10.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 70));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setText("SALIR");
        jPanel10.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 110, 30));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 300, 80));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("TECHSALES");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 230, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 700));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ff9911.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 990, 120));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 204, 153));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/asus.jpg"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 180));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 180, 180));

        jPanel4.setBackground(new java.awt.Color(255, 204, 153));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/intel-core-i5165172.jpg"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 200));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 180, 180));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mouse/m3.jpg"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 180));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, 180, 180));

        jPanel6.setBackground(new java.awt.Color(255, 204, 153));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/impresora-epson-ecotank-l3210-multifuncional-pnc11cj68303-.jpg"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 180));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 180, 180));

        jPanel11.setBackground(new java.awt.Color(255, 204, 153));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/auriculares.jpg"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 180));

        jPanel2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 180, 180));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/teclado/te1.jpg"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel12.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 180));

        jPanel2.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 180, 180));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel6.setText("TECLADOS");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 490, 110, 30));

        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel20.setText("TARJETAS GRÁFICAS");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 180, 30));

        jLabel22.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel22.setText("PROCESADORES");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 140, 30));

        jLabel23.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel23.setText("MOUSE");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, 70, 30));

        jLabel24.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel24.setText("IMPRESORA");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 110, 30));

        jLabel25.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel25.setText("AURICULARES");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, 140, 30));

        jTabbedPane1.addTab("tab1", jPanel2);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlProducto1.setBackground(new java.awt.Color(255, 255, 255));
        pnlProducto1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel14.add(pnlProducto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 180, 180));

        pnlProducto2.setBackground(new java.awt.Color(255, 255, 255));
        pnlProducto2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel14.add(pnlProducto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 180, 180));

        pnlProducto3.setBackground(new java.awt.Color(255, 255, 255));
        pnlProducto3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel14.add(pnlProducto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, 180, 180));

        pnlProducto4.setBackground(new java.awt.Color(255, 255, 255));
        pnlProducto4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel14.add(pnlProducto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 180, 180));

        pnlProducto5.setBackground(new java.awt.Color(255, 255, 255));
        pnlProducto5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel14.add(pnlProducto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 180, 180));

        pnlProducto6.setBackground(new java.awt.Color(255, 255, 255));
        pnlProducto6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel14.add(pnlProducto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 180, 180));

        lblProducto1.setBackground(new java.awt.Color(255, 255, 255));
        lblProducto1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto1.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel14.add(lblProducto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 240, 30));

        lblProducto2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto2.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel14.add(lblProducto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 220, 30));

        lblProducto3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto3.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel14.add(lblProducto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 260, 30));

        lblProducto4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto4.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel14.add(lblProducto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 240, 30));

        lblProducto5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto5.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel14.add(lblProducto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, 240, 30));

        lblProducto6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto6.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel14.add(lblProducto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 490, 260, 30));

        btnSiguiente1.setBackground(new java.awt.Color(255, 153, 0));
        btnSiguiente1.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        btnSiguiente1.setText("SIGUIENTE");
        btnSiguiente1.setBorder(null);
        btnSiguiente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguiente1ActionPerformed(evt);
            }
        });
        jPanel14.add(btnSiguiente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 400, 70, 60));

        txtBuscar.setBackground(new java.awt.Color(204, 204, 204));
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        jPanel14.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 330, -1));

        jTabbedPane1.addTab("tab2", jPanel14);

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setForeground(new java.awt.Color(0, 0, 0));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlProducto7.setBackground(new java.awt.Color(255, 255, 255));
        pnlProducto7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel21.add(pnlProducto7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 180, 180));

        lblProducto7.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto7.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel21.add(lblProducto7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 240, 30));

        pnlProducto8.setBackground(new java.awt.Color(255, 255, 255));
        pnlProducto8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel21.add(pnlProducto8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 180, 180));

        lblProducto8.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto8.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel21.add(lblProducto8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 220, 30));

        pnlProducto9.setBackground(new java.awt.Color(255, 255, 255));
        pnlProducto9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel21.add(pnlProducto9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 180, 180));

        lblProducto9.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto9.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel21.add(lblProducto9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 260, 30));

        pnlProducto10.setBackground(new java.awt.Color(255, 255, 255));
        pnlProducto10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel21.add(pnlProducto10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 180, 180));

        lblProducto10.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto10.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel21.add(lblProducto10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 240, 30));

        pnlProducto11.setBackground(new java.awt.Color(255, 255, 255));
        pnlProducto11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel21.add(pnlProducto11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 180, 180));

        lblProducto11.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto11.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel21.add(lblProducto11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 240, 30));

        pnlProducto12.setBackground(new java.awt.Color(255, 255, 255));
        pnlProducto12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel21.add(pnlProducto12, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, 180, 180));

        lblProducto12.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto12.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel21.add(lblProducto12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, 260, 30));

        btnSiguiente2.setBackground(new java.awt.Color(255, 153, 0));
        btnSiguiente2.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        btnSiguiente2.setText("SIGUIENTE");
        btnSiguiente2.setBorder(null);
        btnSiguiente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguiente2ActionPerformed(evt);
            }
        });
        jPanel21.add(btnSiguiente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 400, 70, 60));

        jTabbedPane1.addTab("tab3", jPanel21);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlProducto13.setBackground(new java.awt.Color(255, 255, 255));
        pnlProducto13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel15.add(pnlProducto13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 180, 180));

        lblProducto13.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto13.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel15.add(lblProducto13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 240, 30));

        pnlProducto14.setBackground(new java.awt.Color(255, 255, 255));
        pnlProducto14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel15.add(pnlProducto14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 180, 180));

        lblProducto14.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto14.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel15.add(lblProducto14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 240, 30));

        pnlProducto15.setBackground(new java.awt.Color(255, 255, 255));
        pnlProducto15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel15.add(pnlProducto15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 180, 180));

        lblProducto15.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto15.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel15.add(lblProducto15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 220, 30));

        pnlProducto16.setBackground(new java.awt.Color(255, 255, 255));
        pnlProducto16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel15.add(pnlProducto16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 180, 180));

        lblProducto16.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto16.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel15.add(lblProducto16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 240, 30));

        pnlProducto17.setBackground(new java.awt.Color(255, 255, 255));
        pnlProducto17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel15.add(pnlProducto17, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 180, 180));

        lblProducto17.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto17.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel15.add(lblProducto17, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 260, 30));

        pnlProducto18.setBackground(new java.awt.Color(255, 255, 255));
        pnlProducto18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel15.add(pnlProducto18, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, 180, 180));

        lblProducto18.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto18.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel15.add(lblProducto18, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, 260, 30));

        btnSiguiente3.setBackground(new java.awt.Color(255, 153, 0));
        btnSiguiente3.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        btnSiguiente3.setText("SIGUIENTE");
        btnSiguiente3.setBorder(null);
        btnSiguiente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguiente3ActionPerformed(evt);
            }
        });
        jPanel15.add(btnSiguiente3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 400, 70, 60));

        jTabbedPane1.addTab("tab4", jPanel15);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlProducto19.setBackground(new java.awt.Color(255, 255, 255));
        pnlProducto19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel13.add(pnlProducto19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 180, 180));

        lblProducto19.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto19.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel13.add(lblProducto19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 240, 30));

        pnlProducto20.setBackground(new java.awt.Color(255, 255, 255));
        pnlProducto20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel13.add(pnlProducto20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 180, 180));

        lblProducto20.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto20.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel13.add(lblProducto20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 240, 30));

        pnlProducto21.setBackground(new java.awt.Color(255, 255, 255));
        pnlProducto21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel13.add(pnlProducto21, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 180, 180));

        lblProducto21.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto21.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel13.add(lblProducto21, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 220, 30));

        pnlProducto22.setBackground(new java.awt.Color(255, 255, 255));
        pnlProducto22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel13.add(pnlProducto22, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 180, 180));

        lblProducto22.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto22.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel13.add(lblProducto22, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 240, 30));

        pnlProducto23.setBackground(new java.awt.Color(255, 255, 255));
        pnlProducto23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel13.add(pnlProducto23, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 180, 180));

        lblProducto23.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto23.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel13.add(lblProducto23, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 260, 30));

        pnlProducto24.setBackground(new java.awt.Color(255, 255, 255));
        pnlProducto24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel13.add(pnlProducto24, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, 180, 180));

        lblProducto24.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto24.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel13.add(lblProducto24, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, 260, 30));

        btnSiguiente4.setBackground(new java.awt.Color(255, 153, 0));
        btnSiguiente4.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        btnSiguiente4.setText("SIGUIENTE");
        btnSiguiente4.setBorder(null);
        btnSiguiente4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguiente4ActionPerformed(evt);
            }
        });
        jPanel13.add(btnSiguiente4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 400, 70, 60));

        jTabbedPane1.addTab("tab5", jPanel13);

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlProducto25.setBackground(new java.awt.Color(255, 255, 255));
        pnlProducto25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel16.add(pnlProducto25, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 180, 180));

        lblProducto25.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto25.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel16.add(lblProducto25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 240, 30));

        pnlProducto26.setBackground(new java.awt.Color(255, 255, 255));
        pnlProducto26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel16.add(pnlProducto26, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 180, 180));

        lblProducto26.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto26.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel16.add(lblProducto26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 240, 30));

        pnlProducto27.setBackground(new java.awt.Color(255, 255, 255));
        pnlProducto27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel16.add(pnlProducto27, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 180, 180));

        lblProducto27.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto27.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel16.add(lblProducto27, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 220, 30));

        pnlProducto28.setBackground(new java.awt.Color(255, 255, 255));
        pnlProducto28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel16.add(pnlProducto28, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 180, 180));

        lblProducto28.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto28.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel16.add(lblProducto28, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 240, 30));

        pnlProducto29.setBackground(new java.awt.Color(255, 255, 255));
        pnlProducto29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel16.add(pnlProducto29, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 180, 180));

        lblProducto29.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto29.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel16.add(lblProducto29, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 260, 30));

        pnlProducto30.setBackground(new java.awt.Color(255, 255, 255));
        pnlProducto30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel16.add(pnlProducto30, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, 180, 180));

        lblProducto30.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto30.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel16.add(lblProducto30, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, 260, 30));

        btnSiguiente5.setBackground(new java.awt.Color(255, 153, 0));
        btnSiguiente5.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        btnSiguiente5.setText("SIGUIENTE");
        btnSiguiente5.setBorder(null);
        btnSiguiente5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguiente5ActionPerformed(evt);
            }
        });
        jPanel16.add(btnSiguiente5, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 400, 70, 60));

        jTabbedPane1.addTab("tab6", jPanel16);

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlProducto31.setBackground(new java.awt.Color(255, 255, 255));
        pnlProducto31.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel17.add(pnlProducto31, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 180, 180));

        lblProducto31.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto31.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel17.add(lblProducto31, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 240, 30));

        pnlProducto32.setBackground(new java.awt.Color(255, 255, 255));
        pnlProducto32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel17.add(pnlProducto32, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 180, 180));

        lblProducto32.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto32.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel17.add(lblProducto32, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 240, 30));

        pnlProducto33.setBackground(new java.awt.Color(255, 255, 255));
        pnlProducto33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel17.add(pnlProducto33, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 180, 180));

        lblProducto33.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto33.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel17.add(lblProducto33, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 220, 30));

        pnlProducto34.setBackground(new java.awt.Color(255, 255, 255));
        pnlProducto34.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel17.add(pnlProducto34, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 180, 180));

        lblProducto34.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto34.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel17.add(lblProducto34, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 240, 30));

        pnlProducto35.setBackground(new java.awt.Color(255, 255, 255));
        pnlProducto35.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel17.add(pnlProducto35, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 180, 180));

        lblProducto35.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto35.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel17.add(lblProducto35, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 260, 30));

        pnlProducto36.setBackground(new java.awt.Color(255, 255, 255));
        pnlProducto36.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel17.add(pnlProducto36, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, 180, 180));

        lblProducto36.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblProducto36.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel17.add(lblProducto36, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, 260, 30));

        jTabbedPane1.addTab("tab7", jPanel17);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 990, 580));
        jTabbedPane1.getAccessibleContext().setAccessibleName("tab3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
            System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel10MouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        jTabbedPane1.setSelectedIndex(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void btnSiguiente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguiente2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSiguiente2ActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnSiguiente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguiente1ActionPerformed
        jTabbedPane1.setSelectedIndex(2);        // TODO add your handling code here:
    }//GEN-LAST:event_btnSiguiente1ActionPerformed

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        jTabbedPane1.setSelectedIndex(11);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        jTabbedPane1.setSelectedIndex(9);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        jTabbedPane1.setSelectedIndex(7);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        jTabbedPane1.setSelectedIndex(5);         // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        jTabbedPane1.setSelectedIndex(5);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        jTabbedPane1.setSelectedIndex(3);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // jTabbedPane1.setSelectedIndex(1);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        jTabbedPane1.setSelectedIndex(1);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    private void btnSiguiente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguiente3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSiguiente3ActionPerformed

    private void btnSiguiente4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguiente4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSiguiente4ActionPerformed

    private void btnSiguiente5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguiente5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSiguiente5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Catalogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente1;
    private javax.swing.JButton btnSiguiente2;
    private javax.swing.JButton btnSiguiente3;
    private javax.swing.JButton btnSiguiente4;
    private javax.swing.JButton btnSiguiente5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblProducto1;
    private javax.swing.JLabel lblProducto10;
    private javax.swing.JLabel lblProducto11;
    private javax.swing.JLabel lblProducto12;
    private javax.swing.JLabel lblProducto13;
    private javax.swing.JLabel lblProducto14;
    private javax.swing.JLabel lblProducto15;
    private javax.swing.JLabel lblProducto16;
    private javax.swing.JLabel lblProducto17;
    private javax.swing.JLabel lblProducto18;
    private javax.swing.JLabel lblProducto19;
    private javax.swing.JLabel lblProducto2;
    private javax.swing.JLabel lblProducto20;
    private javax.swing.JLabel lblProducto21;
    private javax.swing.JLabel lblProducto22;
    private javax.swing.JLabel lblProducto23;
    private javax.swing.JLabel lblProducto24;
    private javax.swing.JLabel lblProducto25;
    private javax.swing.JLabel lblProducto26;
    private javax.swing.JLabel lblProducto27;
    private javax.swing.JLabel lblProducto28;
    private javax.swing.JLabel lblProducto29;
    private javax.swing.JLabel lblProducto3;
    private javax.swing.JLabel lblProducto30;
    private javax.swing.JLabel lblProducto31;
    private javax.swing.JLabel lblProducto32;
    private javax.swing.JLabel lblProducto33;
    private javax.swing.JLabel lblProducto34;
    private javax.swing.JLabel lblProducto35;
    private javax.swing.JLabel lblProducto36;
    private javax.swing.JLabel lblProducto4;
    private javax.swing.JLabel lblProducto5;
    private javax.swing.JLabel lblProducto6;
    private javax.swing.JLabel lblProducto7;
    private javax.swing.JLabel lblProducto8;
    private javax.swing.JLabel lblProducto9;
    private javax.swing.JPanel pnlProducto1;
    private javax.swing.JPanel pnlProducto10;
    private javax.swing.JPanel pnlProducto11;
    private javax.swing.JPanel pnlProducto12;
    private javax.swing.JPanel pnlProducto13;
    private javax.swing.JPanel pnlProducto14;
    private javax.swing.JPanel pnlProducto15;
    private javax.swing.JPanel pnlProducto16;
    private javax.swing.JPanel pnlProducto17;
    private javax.swing.JPanel pnlProducto18;
    private javax.swing.JPanel pnlProducto19;
    private javax.swing.JPanel pnlProducto2;
    private javax.swing.JPanel pnlProducto20;
    private javax.swing.JPanel pnlProducto21;
    private javax.swing.JPanel pnlProducto22;
    private javax.swing.JPanel pnlProducto23;
    private javax.swing.JPanel pnlProducto24;
    private javax.swing.JPanel pnlProducto25;
    private javax.swing.JPanel pnlProducto26;
    private javax.swing.JPanel pnlProducto27;
    private javax.swing.JPanel pnlProducto28;
    private javax.swing.JPanel pnlProducto29;
    private javax.swing.JPanel pnlProducto3;
    private javax.swing.JPanel pnlProducto30;
    private javax.swing.JPanel pnlProducto31;
    private javax.swing.JPanel pnlProducto32;
    private javax.swing.JPanel pnlProducto33;
    private javax.swing.JPanel pnlProducto34;
    private javax.swing.JPanel pnlProducto35;
    private javax.swing.JPanel pnlProducto36;
    private javax.swing.JPanel pnlProducto4;
    private javax.swing.JPanel pnlProducto5;
    private javax.swing.JPanel pnlProducto6;
    private javax.swing.JPanel pnlProducto7;
    private javax.swing.JPanel pnlProducto8;
    private javax.swing.JPanel pnlProducto9;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
